package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class ChatterActivity extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public ChatterActivity() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : CommentCount of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean CommentCount__is_set = false;

    private java.lang.Integer CommentCount;

    public java.lang.Integer getCommentCount() {
      return CommentCount;
    }

    public void setCommentCount(java.lang.Integer CommentCount) {
      this.CommentCount = CommentCount;
      CommentCount__is_set = true;
    }

    protected void setCommentCount(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CommentCount", "urn:sobject.enterprise.soap.sforce.com","CommentCount","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setCommentCount((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("CommentCount", "urn:sobject.enterprise.soap.sforce.com","CommentCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldCommentCount(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CommentCount", "urn:sobject.enterprise.soap.sforce.com","CommentCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), CommentCount, CommentCount__is_set);
    }

    /**
     * element : CommentReceivedCount of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean CommentReceivedCount__is_set = false;

    private java.lang.Integer CommentReceivedCount;

    public java.lang.Integer getCommentReceivedCount() {
      return CommentReceivedCount;
    }

    public void setCommentReceivedCount(java.lang.Integer CommentReceivedCount) {
      this.CommentReceivedCount = CommentReceivedCount;
      CommentReceivedCount__is_set = true;
    }

    protected void setCommentReceivedCount(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CommentReceivedCount", "urn:sobject.enterprise.soap.sforce.com","CommentReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setCommentReceivedCount((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("CommentReceivedCount", "urn:sobject.enterprise.soap.sforce.com","CommentReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldCommentReceivedCount(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CommentReceivedCount", "urn:sobject.enterprise.soap.sforce.com","CommentReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), CommentReceivedCount, CommentReceivedCount__is_set);
    }

    /**
     * element : InfluenceRawRank of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean InfluenceRawRank__is_set = false;

    private java.lang.Integer InfluenceRawRank;

    public java.lang.Integer getInfluenceRawRank() {
      return InfluenceRawRank;
    }

    public void setInfluenceRawRank(java.lang.Integer InfluenceRawRank) {
      this.InfluenceRawRank = InfluenceRawRank;
      InfluenceRawRank__is_set = true;
    }

    protected void setInfluenceRawRank(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("InfluenceRawRank", "urn:sobject.enterprise.soap.sforce.com","InfluenceRawRank","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setInfluenceRawRank((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("InfluenceRawRank", "urn:sobject.enterprise.soap.sforce.com","InfluenceRawRank","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldInfluenceRawRank(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("InfluenceRawRank", "urn:sobject.enterprise.soap.sforce.com","InfluenceRawRank","http://www.w3.org/2001/XMLSchema","int",0,1,true), InfluenceRawRank, InfluenceRawRank__is_set);
    }

    /**
     * element : LikeReceivedCount of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean LikeReceivedCount__is_set = false;

    private java.lang.Integer LikeReceivedCount;

    public java.lang.Integer getLikeReceivedCount() {
      return LikeReceivedCount;
    }

    public void setLikeReceivedCount(java.lang.Integer LikeReceivedCount) {
      this.LikeReceivedCount = LikeReceivedCount;
      LikeReceivedCount__is_set = true;
    }

    protected void setLikeReceivedCount(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LikeReceivedCount", "urn:sobject.enterprise.soap.sforce.com","LikeReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setLikeReceivedCount((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("LikeReceivedCount", "urn:sobject.enterprise.soap.sforce.com","LikeReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldLikeReceivedCount(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LikeReceivedCount", "urn:sobject.enterprise.soap.sforce.com","LikeReceivedCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), LikeReceivedCount, LikeReceivedCount__is_set);
    }

    /**
     * element : ParentId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean ParentId__is_set = false;

    private java.lang.String ParentId;

    public java.lang.String getParentId() {
      return ParentId;
    }

    public void setParentId(java.lang.String ParentId) {
      this.ParentId = ParentId;
      ParentId__is_set = true;
    }

    protected void setParentId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ParentId", "urn:sobject.enterprise.soap.sforce.com","ParentId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setParentId(__typeMapper.readString(__in, _lookupTypeInfo("ParentId", "urn:sobject.enterprise.soap.sforce.com","ParentId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldParentId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ParentId", "urn:sobject.enterprise.soap.sforce.com","ParentId","urn:enterprise.soap.sforce.com","ID",0,1,true), ParentId, ParentId__is_set);
    }

    /**
     * element : PostCount of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean PostCount__is_set = false;

    private java.lang.Integer PostCount;

    public java.lang.Integer getPostCount() {
      return PostCount;
    }

    public void setPostCount(java.lang.Integer PostCount) {
      this.PostCount = PostCount;
      PostCount__is_set = true;
    }

    protected void setPostCount(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("PostCount", "urn:sobject.enterprise.soap.sforce.com","PostCount","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setPostCount((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("PostCount", "urn:sobject.enterprise.soap.sforce.com","PostCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldPostCount(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("PostCount", "urn:sobject.enterprise.soap.sforce.com","PostCount","http://www.w3.org/2001/XMLSchema","int",0,1,true), PostCount, PostCount__is_set);
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    protected void setSystemModstamp(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldSystemModstamp(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), SystemModstamp, SystemModstamp__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "ChatterActivity");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ChatterActivity ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldCommentCount(__out, __typeMapper);
      writeFieldCommentReceivedCount(__out, __typeMapper);
      writeFieldInfluenceRawRank(__out, __typeMapper);
      writeFieldLikeReceivedCount(__out, __typeMapper);
      writeFieldParentId(__out, __typeMapper);
      writeFieldPostCount(__out, __typeMapper);
      writeFieldSystemModstamp(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setCommentCount(__in, __typeMapper);
      setCommentReceivedCount(__in, __typeMapper);
      setInfluenceRawRank(__in, __typeMapper);
      setLikeReceivedCount(__in, __typeMapper);
      setParentId(__in, __typeMapper);
      setPostCount(__in, __typeMapper);
      setSystemModstamp(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "CommentCount", CommentCount);
      toStringHelper(sb, "CommentReceivedCount", CommentReceivedCount);
      toStringHelper(sb, "InfluenceRawRank", InfluenceRawRank);
      toStringHelper(sb, "LikeReceivedCount", LikeReceivedCount);
      toStringHelper(sb, "ParentId", ParentId);
      toStringHelper(sb, "PostCount", PostCount);
      toStringHelper(sb, "SystemModstamp", SystemModstamp);
    }


}
