package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class CronTrigger extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public CronTrigger() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    protected void setCreatedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldCreatedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), CreatedBy, CreatedBy__is_set);
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    protected void setCreatedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setCreatedById(__typeMapper.readString(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCreatedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), CreatedById, CreatedById__is_set);
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    protected void setCreatedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldCreatedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), CreatedDate, CreatedDate__is_set);
    }

    /**
     * element : CronExpression of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean CronExpression__is_set = false;

    private java.lang.String CronExpression;

    public java.lang.String getCronExpression() {
      return CronExpression;
    }

    public void setCronExpression(java.lang.String CronExpression) {
      this.CronExpression = CronExpression;
      CronExpression__is_set = true;
    }

    protected void setCronExpression(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CronExpression", "urn:sobject.enterprise.soap.sforce.com","CronExpression","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setCronExpression(__typeMapper.readString(__in, _lookupTypeInfo("CronExpression", "urn:sobject.enterprise.soap.sforce.com","CronExpression","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCronExpression(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CronExpression", "urn:sobject.enterprise.soap.sforce.com","CronExpression","http://www.w3.org/2001/XMLSchema","string",0,1,true), CronExpression, CronExpression__is_set);
    }

    /**
     * element : CronJobDetail of type {urn:sobject.enterprise.soap.sforce.com}CronJobDetail
     * java type: com.sforce.soap.enterprise.sobject.CronJobDetail
     */
    private boolean CronJobDetail__is_set = false;

    private com.sforce.soap.enterprise.sobject.CronJobDetail CronJobDetail;

    public com.sforce.soap.enterprise.sobject.CronJobDetail getCronJobDetail() {
      return CronJobDetail;
    }

    public void setCronJobDetail(com.sforce.soap.enterprise.sobject.CronJobDetail CronJobDetail) {
      this.CronJobDetail = CronJobDetail;
      CronJobDetail__is_set = true;
    }

    protected void setCronJobDetail(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CronJobDetail", "urn:sobject.enterprise.soap.sforce.com","CronJobDetail","urn:sobject.enterprise.soap.sforce.com","CronJobDetail",0,1,true))) {
        setCronJobDetail((com.sforce.soap.enterprise.sobject.CronJobDetail)__typeMapper.readObject(__in, _lookupTypeInfo("CronJobDetail", "urn:sobject.enterprise.soap.sforce.com","CronJobDetail","urn:sobject.enterprise.soap.sforce.com","CronJobDetail",0,1,true), com.sforce.soap.enterprise.sobject.CronJobDetail.class));
      }
    }

    private void writeFieldCronJobDetail(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CronJobDetail", "urn:sobject.enterprise.soap.sforce.com","CronJobDetail","urn:sobject.enterprise.soap.sforce.com","CronJobDetail",0,1,true), CronJobDetail, CronJobDetail__is_set);
    }

    /**
     * element : CronJobDetailId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean CronJobDetailId__is_set = false;

    private java.lang.String CronJobDetailId;

    public java.lang.String getCronJobDetailId() {
      return CronJobDetailId;
    }

    public void setCronJobDetailId(java.lang.String CronJobDetailId) {
      this.CronJobDetailId = CronJobDetailId;
      CronJobDetailId__is_set = true;
    }

    protected void setCronJobDetailId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CronJobDetailId", "urn:sobject.enterprise.soap.sforce.com","CronJobDetailId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setCronJobDetailId(__typeMapper.readString(__in, _lookupTypeInfo("CronJobDetailId", "urn:sobject.enterprise.soap.sforce.com","CronJobDetailId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCronJobDetailId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CronJobDetailId", "urn:sobject.enterprise.soap.sforce.com","CronJobDetailId","urn:enterprise.soap.sforce.com","ID",0,1,true), CronJobDetailId, CronJobDetailId__is_set);
    }

    /**
     * element : EndTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean EndTime__is_set = false;

    private java.util.Calendar EndTime;

    public java.util.Calendar getEndTime() {
      return EndTime;
    }

    public void setEndTime(java.util.Calendar EndTime) {
      this.EndTime = EndTime;
      EndTime__is_set = true;
    }

    protected void setEndTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("EndTime", "urn:sobject.enterprise.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setEndTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("EndTime", "urn:sobject.enterprise.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldEndTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("EndTime", "urn:sobject.enterprise.soap.sforce.com","EndTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), EndTime, EndTime__is_set);
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    protected void setLastModifiedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldLastModifiedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), LastModifiedBy, LastModifiedBy__is_set);
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    protected void setLastModifiedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setLastModifiedById(__typeMapper.readString(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLastModifiedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), LastModifiedById, LastModifiedById__is_set);
    }

    /**
     * element : NextFireTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean NextFireTime__is_set = false;

    private java.util.Calendar NextFireTime;

    public java.util.Calendar getNextFireTime() {
      return NextFireTime;
    }

    public void setNextFireTime(java.util.Calendar NextFireTime) {
      this.NextFireTime = NextFireTime;
      NextFireTime__is_set = true;
    }

    protected void setNextFireTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("NextFireTime", "urn:sobject.enterprise.soap.sforce.com","NextFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setNextFireTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("NextFireTime", "urn:sobject.enterprise.soap.sforce.com","NextFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldNextFireTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("NextFireTime", "urn:sobject.enterprise.soap.sforce.com","NextFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), NextFireTime, NextFireTime__is_set);
    }

    /**
     * element : OwnerId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean OwnerId__is_set = false;

    private java.lang.String OwnerId;

    public java.lang.String getOwnerId() {
      return OwnerId;
    }

    public void setOwnerId(java.lang.String OwnerId) {
      this.OwnerId = OwnerId;
      OwnerId__is_set = true;
    }

    protected void setOwnerId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("OwnerId", "urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setOwnerId(__typeMapper.readString(__in, _lookupTypeInfo("OwnerId", "urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldOwnerId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("OwnerId", "urn:sobject.enterprise.soap.sforce.com","OwnerId","urn:enterprise.soap.sforce.com","ID",0,1,true), OwnerId, OwnerId__is_set);
    }

    /**
     * element : PreviousFireTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean PreviousFireTime__is_set = false;

    private java.util.Calendar PreviousFireTime;

    public java.util.Calendar getPreviousFireTime() {
      return PreviousFireTime;
    }

    public void setPreviousFireTime(java.util.Calendar PreviousFireTime) {
      this.PreviousFireTime = PreviousFireTime;
      PreviousFireTime__is_set = true;
    }

    protected void setPreviousFireTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("PreviousFireTime", "urn:sobject.enterprise.soap.sforce.com","PreviousFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setPreviousFireTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("PreviousFireTime", "urn:sobject.enterprise.soap.sforce.com","PreviousFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldPreviousFireTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("PreviousFireTime", "urn:sobject.enterprise.soap.sforce.com","PreviousFireTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), PreviousFireTime, PreviousFireTime__is_set);
    }

    /**
     * element : StartTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean StartTime__is_set = false;

    private java.util.Calendar StartTime;

    public java.util.Calendar getStartTime() {
      return StartTime;
    }

    public void setStartTime(java.util.Calendar StartTime) {
      this.StartTime = StartTime;
      StartTime__is_set = true;
    }

    protected void setStartTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("StartTime", "urn:sobject.enterprise.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setStartTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("StartTime", "urn:sobject.enterprise.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldStartTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("StartTime", "urn:sobject.enterprise.soap.sforce.com","StartTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), StartTime, StartTime__is_set);
    }

    /**
     * element : State of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean State__is_set = false;

    private java.lang.String State;

    public java.lang.String getState() {
      return State;
    }

    public void setState(java.lang.String State) {
      this.State = State;
      State__is_set = true;
    }

    protected void setState(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("State", "urn:sobject.enterprise.soap.sforce.com","State","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setState(__typeMapper.readString(__in, _lookupTypeInfo("State", "urn:sobject.enterprise.soap.sforce.com","State","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldState(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("State", "urn:sobject.enterprise.soap.sforce.com","State","http://www.w3.org/2001/XMLSchema","string",0,1,true), State, State__is_set);
    }

    /**
     * element : TimeZoneSidKey of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean TimeZoneSidKey__is_set = false;

    private java.lang.String TimeZoneSidKey;

    public java.lang.String getTimeZoneSidKey() {
      return TimeZoneSidKey;
    }

    public void setTimeZoneSidKey(java.lang.String TimeZoneSidKey) {
      this.TimeZoneSidKey = TimeZoneSidKey;
      TimeZoneSidKey__is_set = true;
    }

    protected void setTimeZoneSidKey(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("TimeZoneSidKey", "urn:sobject.enterprise.soap.sforce.com","TimeZoneSidKey","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setTimeZoneSidKey(__typeMapper.readString(__in, _lookupTypeInfo("TimeZoneSidKey", "urn:sobject.enterprise.soap.sforce.com","TimeZoneSidKey","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldTimeZoneSidKey(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("TimeZoneSidKey", "urn:sobject.enterprise.soap.sforce.com","TimeZoneSidKey","http://www.w3.org/2001/XMLSchema","string",0,1,true), TimeZoneSidKey, TimeZoneSidKey__is_set);
    }

    /**
     * element : TimesTriggered of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean TimesTriggered__is_set = false;

    private java.lang.Integer TimesTriggered;

    public java.lang.Integer getTimesTriggered() {
      return TimesTriggered;
    }

    public void setTimesTriggered(java.lang.Integer TimesTriggered) {
      this.TimesTriggered = TimesTriggered;
      TimesTriggered__is_set = true;
    }

    protected void setTimesTriggered(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("TimesTriggered", "urn:sobject.enterprise.soap.sforce.com","TimesTriggered","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setTimesTriggered((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("TimesTriggered", "urn:sobject.enterprise.soap.sforce.com","TimesTriggered","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldTimesTriggered(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("TimesTriggered", "urn:sobject.enterprise.soap.sforce.com","TimesTriggered","http://www.w3.org/2001/XMLSchema","int",0,1,true), TimesTriggered, TimesTriggered__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "CronTrigger");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CronTrigger ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldCreatedBy(__out, __typeMapper);
      writeFieldCreatedById(__out, __typeMapper);
      writeFieldCreatedDate(__out, __typeMapper);
      writeFieldCronExpression(__out, __typeMapper);
      writeFieldCronJobDetail(__out, __typeMapper);
      writeFieldCronJobDetailId(__out, __typeMapper);
      writeFieldEndTime(__out, __typeMapper);
      writeFieldLastModifiedBy(__out, __typeMapper);
      writeFieldLastModifiedById(__out, __typeMapper);
      writeFieldNextFireTime(__out, __typeMapper);
      writeFieldOwnerId(__out, __typeMapper);
      writeFieldPreviousFireTime(__out, __typeMapper);
      writeFieldStartTime(__out, __typeMapper);
      writeFieldState(__out, __typeMapper);
      writeFieldTimeZoneSidKey(__out, __typeMapper);
      writeFieldTimesTriggered(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setCreatedBy(__in, __typeMapper);
      setCreatedById(__in, __typeMapper);
      setCreatedDate(__in, __typeMapper);
      setCronExpression(__in, __typeMapper);
      setCronJobDetail(__in, __typeMapper);
      setCronJobDetailId(__in, __typeMapper);
      setEndTime(__in, __typeMapper);
      setLastModifiedBy(__in, __typeMapper);
      setLastModifiedById(__in, __typeMapper);
      setNextFireTime(__in, __typeMapper);
      setOwnerId(__in, __typeMapper);
      setPreviousFireTime(__in, __typeMapper);
      setStartTime(__in, __typeMapper);
      setState(__in, __typeMapper);
      setTimeZoneSidKey(__in, __typeMapper);
      setTimesTriggered(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "CreatedBy", CreatedBy);
      toStringHelper(sb, "CreatedById", CreatedById);
      toStringHelper(sb, "CreatedDate", CreatedDate);
      toStringHelper(sb, "CronExpression", CronExpression);
      toStringHelper(sb, "CronJobDetail", CronJobDetail);
      toStringHelper(sb, "CronJobDetailId", CronJobDetailId);
      toStringHelper(sb, "EndTime", EndTime);
      toStringHelper(sb, "LastModifiedBy", LastModifiedBy);
      toStringHelper(sb, "LastModifiedById", LastModifiedById);
      toStringHelper(sb, "NextFireTime", NextFireTime);
      toStringHelper(sb, "OwnerId", OwnerId);
      toStringHelper(sb, "PreviousFireTime", PreviousFireTime);
      toStringHelper(sb, "StartTime", StartTime);
      toStringHelper(sb, "State", State);
      toStringHelper(sb, "TimeZoneSidKey", TimeZoneSidKey);
      toStringHelper(sb, "TimesTriggered", TimesTriggered);
    }


}
