package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class EmailServicesFunction extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public EmailServicesFunction() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : AddressInactiveAction of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean AddressInactiveAction__is_set = false;

    private java.lang.String AddressInactiveAction;

    public java.lang.String getAddressInactiveAction() {
      return AddressInactiveAction;
    }

    public void setAddressInactiveAction(java.lang.String AddressInactiveAction) {
      this.AddressInactiveAction = AddressInactiveAction;
      AddressInactiveAction__is_set = true;
    }

    protected void setAddressInactiveAction(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AddressInactiveAction", "urn:sobject.enterprise.soap.sforce.com","AddressInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAddressInactiveAction(__typeMapper.readString(__in, _lookupTypeInfo("AddressInactiveAction", "urn:sobject.enterprise.soap.sforce.com","AddressInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAddressInactiveAction(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AddressInactiveAction", "urn:sobject.enterprise.soap.sforce.com","AddressInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), AddressInactiveAction, AddressInactiveAction__is_set);
    }

    /**
     * element : Addresses of type {urn:enterprise.soap.sforce.com}QueryResult
     * java type: com.sforce.soap.enterprise.QueryResult
     */
    private boolean Addresses__is_set = false;

    private com.sforce.soap.enterprise.QueryResult Addresses;

    public com.sforce.soap.enterprise.QueryResult getAddresses() {
      return Addresses;
    }

    public void setAddresses(com.sforce.soap.enterprise.QueryResult Addresses) {
      this.Addresses = Addresses;
      Addresses__is_set = true;
    }

    protected void setAddresses(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Addresses", "urn:sobject.enterprise.soap.sforce.com","Addresses","urn:enterprise.soap.sforce.com","QueryResult",0,1,true))) {
        setAddresses((com.sforce.soap.enterprise.QueryResult)__typeMapper.readObject(__in, _lookupTypeInfo("Addresses", "urn:sobject.enterprise.soap.sforce.com","Addresses","urn:enterprise.soap.sforce.com","QueryResult",0,1,true), com.sforce.soap.enterprise.QueryResult.class));
      }
    }

    private void writeFieldAddresses(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Addresses", "urn:sobject.enterprise.soap.sforce.com","Addresses","urn:enterprise.soap.sforce.com","QueryResult",0,1,true), Addresses, Addresses__is_set);
    }

    /**
     * element : ApexClassId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean ApexClassId__is_set = false;

    private java.lang.String ApexClassId;

    public java.lang.String getApexClassId() {
      return ApexClassId;
    }

    public void setApexClassId(java.lang.String ApexClassId) {
      this.ApexClassId = ApexClassId;
      ApexClassId__is_set = true;
    }

    protected void setApexClassId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ApexClassId", "urn:sobject.enterprise.soap.sforce.com","ApexClassId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setApexClassId(__typeMapper.readString(__in, _lookupTypeInfo("ApexClassId", "urn:sobject.enterprise.soap.sforce.com","ApexClassId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldApexClassId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ApexClassId", "urn:sobject.enterprise.soap.sforce.com","ApexClassId","urn:enterprise.soap.sforce.com","ID",0,1,true), ApexClassId, ApexClassId__is_set);
    }

    /**
     * element : AttachmentOption of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean AttachmentOption__is_set = false;

    private java.lang.String AttachmentOption;

    public java.lang.String getAttachmentOption() {
      return AttachmentOption;
    }

    public void setAttachmentOption(java.lang.String AttachmentOption) {
      this.AttachmentOption = AttachmentOption;
      AttachmentOption__is_set = true;
    }

    protected void setAttachmentOption(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AttachmentOption", "urn:sobject.enterprise.soap.sforce.com","AttachmentOption","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAttachmentOption(__typeMapper.readString(__in, _lookupTypeInfo("AttachmentOption", "urn:sobject.enterprise.soap.sforce.com","AttachmentOption","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAttachmentOption(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AttachmentOption", "urn:sobject.enterprise.soap.sforce.com","AttachmentOption","http://www.w3.org/2001/XMLSchema","string",0,1,true), AttachmentOption, AttachmentOption__is_set);
    }

    /**
     * element : AuthenticationFailureAction of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean AuthenticationFailureAction__is_set = false;

    private java.lang.String AuthenticationFailureAction;

    public java.lang.String getAuthenticationFailureAction() {
      return AuthenticationFailureAction;
    }

    public void setAuthenticationFailureAction(java.lang.String AuthenticationFailureAction) {
      this.AuthenticationFailureAction = AuthenticationFailureAction;
      AuthenticationFailureAction__is_set = true;
    }

    protected void setAuthenticationFailureAction(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AuthenticationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthenticationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAuthenticationFailureAction(__typeMapper.readString(__in, _lookupTypeInfo("AuthenticationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthenticationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAuthenticationFailureAction(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AuthenticationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthenticationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), AuthenticationFailureAction, AuthenticationFailureAction__is_set);
    }

    /**
     * element : AuthorizationFailureAction of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean AuthorizationFailureAction__is_set = false;

    private java.lang.String AuthorizationFailureAction;

    public java.lang.String getAuthorizationFailureAction() {
      return AuthorizationFailureAction;
    }

    public void setAuthorizationFailureAction(java.lang.String AuthorizationFailureAction) {
      this.AuthorizationFailureAction = AuthorizationFailureAction;
      AuthorizationFailureAction__is_set = true;
    }

    protected void setAuthorizationFailureAction(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AuthorizationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthorizationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAuthorizationFailureAction(__typeMapper.readString(__in, _lookupTypeInfo("AuthorizationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthorizationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAuthorizationFailureAction(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AuthorizationFailureAction", "urn:sobject.enterprise.soap.sforce.com","AuthorizationFailureAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), AuthorizationFailureAction, AuthorizationFailureAction__is_set);
    }

    /**
     * element : AuthorizedSenders of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean AuthorizedSenders__is_set = false;

    private java.lang.String AuthorizedSenders;

    public java.lang.String getAuthorizedSenders() {
      return AuthorizedSenders;
    }

    public void setAuthorizedSenders(java.lang.String AuthorizedSenders) {
      this.AuthorizedSenders = AuthorizedSenders;
      AuthorizedSenders__is_set = true;
    }

    protected void setAuthorizedSenders(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("AuthorizedSenders", "urn:sobject.enterprise.soap.sforce.com","AuthorizedSenders","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAuthorizedSenders(__typeMapper.readString(__in, _lookupTypeInfo("AuthorizedSenders", "urn:sobject.enterprise.soap.sforce.com","AuthorizedSenders","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAuthorizedSenders(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("AuthorizedSenders", "urn:sobject.enterprise.soap.sforce.com","AuthorizedSenders","http://www.w3.org/2001/XMLSchema","string",0,1,true), AuthorizedSenders, AuthorizedSenders__is_set);
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    protected void setCreatedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldCreatedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), CreatedBy, CreatedBy__is_set);
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    protected void setCreatedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setCreatedById(__typeMapper.readString(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCreatedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), CreatedById, CreatedById__is_set);
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    protected void setCreatedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldCreatedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), CreatedDate, CreatedDate__is_set);
    }

    /**
     * element : ErrorRoutingAddress of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean ErrorRoutingAddress__is_set = false;

    private java.lang.String ErrorRoutingAddress;

    public java.lang.String getErrorRoutingAddress() {
      return ErrorRoutingAddress;
    }

    public void setErrorRoutingAddress(java.lang.String ErrorRoutingAddress) {
      this.ErrorRoutingAddress = ErrorRoutingAddress;
      ErrorRoutingAddress__is_set = true;
    }

    protected void setErrorRoutingAddress(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ErrorRoutingAddress", "urn:sobject.enterprise.soap.sforce.com","ErrorRoutingAddress","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setErrorRoutingAddress(__typeMapper.readString(__in, _lookupTypeInfo("ErrorRoutingAddress", "urn:sobject.enterprise.soap.sforce.com","ErrorRoutingAddress","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldErrorRoutingAddress(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ErrorRoutingAddress", "urn:sobject.enterprise.soap.sforce.com","ErrorRoutingAddress","http://www.w3.org/2001/XMLSchema","string",0,1,true), ErrorRoutingAddress, ErrorRoutingAddress__is_set);
    }

    /**
     * element : FunctionInactiveAction of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean FunctionInactiveAction__is_set = false;

    private java.lang.String FunctionInactiveAction;

    public java.lang.String getFunctionInactiveAction() {
      return FunctionInactiveAction;
    }

    public void setFunctionInactiveAction(java.lang.String FunctionInactiveAction) {
      this.FunctionInactiveAction = FunctionInactiveAction;
      FunctionInactiveAction__is_set = true;
    }

    protected void setFunctionInactiveAction(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("FunctionInactiveAction", "urn:sobject.enterprise.soap.sforce.com","FunctionInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setFunctionInactiveAction(__typeMapper.readString(__in, _lookupTypeInfo("FunctionInactiveAction", "urn:sobject.enterprise.soap.sforce.com","FunctionInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldFunctionInactiveAction(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("FunctionInactiveAction", "urn:sobject.enterprise.soap.sforce.com","FunctionInactiveAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), FunctionInactiveAction, FunctionInactiveAction__is_set);
    }

    /**
     * element : FunctionName of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean FunctionName__is_set = false;

    private java.lang.String FunctionName;

    public java.lang.String getFunctionName() {
      return FunctionName;
    }

    public void setFunctionName(java.lang.String FunctionName) {
      this.FunctionName = FunctionName;
      FunctionName__is_set = true;
    }

    protected void setFunctionName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("FunctionName", "urn:sobject.enterprise.soap.sforce.com","FunctionName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setFunctionName(__typeMapper.readString(__in, _lookupTypeInfo("FunctionName", "urn:sobject.enterprise.soap.sforce.com","FunctionName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldFunctionName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("FunctionName", "urn:sobject.enterprise.soap.sforce.com","FunctionName","http://www.w3.org/2001/XMLSchema","string",0,1,true), FunctionName, FunctionName__is_set);
    }

    /**
     * element : IsActive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsActive__is_set = false;

    private java.lang.Boolean IsActive;

    public java.lang.Boolean getIsActive() {
      return IsActive;
    }

    public void setIsActive(java.lang.Boolean IsActive) {
      this.IsActive = IsActive;
      IsActive__is_set = true;
    }

    protected void setIsActive(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsActive((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsActive(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsActive, IsActive__is_set);
    }

    /**
     * element : IsAuthenticationRequired of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsAuthenticationRequired__is_set = false;

    private java.lang.Boolean IsAuthenticationRequired;

    public java.lang.Boolean getIsAuthenticationRequired() {
      return IsAuthenticationRequired;
    }

    public void setIsAuthenticationRequired(java.lang.Boolean IsAuthenticationRequired) {
      this.IsAuthenticationRequired = IsAuthenticationRequired;
      IsAuthenticationRequired__is_set = true;
    }

    protected void setIsAuthenticationRequired(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsAuthenticationRequired", "urn:sobject.enterprise.soap.sforce.com","IsAuthenticationRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsAuthenticationRequired((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsAuthenticationRequired", "urn:sobject.enterprise.soap.sforce.com","IsAuthenticationRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsAuthenticationRequired(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsAuthenticationRequired", "urn:sobject.enterprise.soap.sforce.com","IsAuthenticationRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsAuthenticationRequired, IsAuthenticationRequired__is_set);
    }

    /**
     * element : IsErrorRoutingEnabled of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsErrorRoutingEnabled__is_set = false;

    private java.lang.Boolean IsErrorRoutingEnabled;

    public java.lang.Boolean getIsErrorRoutingEnabled() {
      return IsErrorRoutingEnabled;
    }

    public void setIsErrorRoutingEnabled(java.lang.Boolean IsErrorRoutingEnabled) {
      this.IsErrorRoutingEnabled = IsErrorRoutingEnabled;
      IsErrorRoutingEnabled__is_set = true;
    }

    protected void setIsErrorRoutingEnabled(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsErrorRoutingEnabled", "urn:sobject.enterprise.soap.sforce.com","IsErrorRoutingEnabled","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsErrorRoutingEnabled((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsErrorRoutingEnabled", "urn:sobject.enterprise.soap.sforce.com","IsErrorRoutingEnabled","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsErrorRoutingEnabled(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsErrorRoutingEnabled", "urn:sobject.enterprise.soap.sforce.com","IsErrorRoutingEnabled","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsErrorRoutingEnabled, IsErrorRoutingEnabled__is_set);
    }

    /**
     * element : IsTextAttachmentsAsBinary of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsTextAttachmentsAsBinary__is_set = false;

    private java.lang.Boolean IsTextAttachmentsAsBinary;

    public java.lang.Boolean getIsTextAttachmentsAsBinary() {
      return IsTextAttachmentsAsBinary;
    }

    public void setIsTextAttachmentsAsBinary(java.lang.Boolean IsTextAttachmentsAsBinary) {
      this.IsTextAttachmentsAsBinary = IsTextAttachmentsAsBinary;
      IsTextAttachmentsAsBinary__is_set = true;
    }

    protected void setIsTextAttachmentsAsBinary(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsTextAttachmentsAsBinary", "urn:sobject.enterprise.soap.sforce.com","IsTextAttachmentsAsBinary","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsTextAttachmentsAsBinary((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsTextAttachmentsAsBinary", "urn:sobject.enterprise.soap.sforce.com","IsTextAttachmentsAsBinary","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsTextAttachmentsAsBinary(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsTextAttachmentsAsBinary", "urn:sobject.enterprise.soap.sforce.com","IsTextAttachmentsAsBinary","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsTextAttachmentsAsBinary, IsTextAttachmentsAsBinary__is_set);
    }

    /**
     * element : IsTlsRequired of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsTlsRequired__is_set = false;

    private java.lang.Boolean IsTlsRequired;

    public java.lang.Boolean getIsTlsRequired() {
      return IsTlsRequired;
    }

    public void setIsTlsRequired(java.lang.Boolean IsTlsRequired) {
      this.IsTlsRequired = IsTlsRequired;
      IsTlsRequired__is_set = true;
    }

    protected void setIsTlsRequired(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsTlsRequired", "urn:sobject.enterprise.soap.sforce.com","IsTlsRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsTlsRequired((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsTlsRequired", "urn:sobject.enterprise.soap.sforce.com","IsTlsRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsTlsRequired(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsTlsRequired", "urn:sobject.enterprise.soap.sforce.com","IsTlsRequired","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsTlsRequired, IsTlsRequired__is_set);
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    protected void setLastModifiedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldLastModifiedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), LastModifiedBy, LastModifiedBy__is_set);
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    protected void setLastModifiedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setLastModifiedById(__typeMapper.readString(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLastModifiedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), LastModifiedById, LastModifiedById__is_set);
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    protected void setLastModifiedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldLastModifiedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), LastModifiedDate, LastModifiedDate__is_set);
    }

    /**
     * element : OverLimitAction of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean OverLimitAction__is_set = false;

    private java.lang.String OverLimitAction;

    public java.lang.String getOverLimitAction() {
      return OverLimitAction;
    }

    public void setOverLimitAction(java.lang.String OverLimitAction) {
      this.OverLimitAction = OverLimitAction;
      OverLimitAction__is_set = true;
    }

    protected void setOverLimitAction(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("OverLimitAction", "urn:sobject.enterprise.soap.sforce.com","OverLimitAction","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setOverLimitAction(__typeMapper.readString(__in, _lookupTypeInfo("OverLimitAction", "urn:sobject.enterprise.soap.sforce.com","OverLimitAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldOverLimitAction(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("OverLimitAction", "urn:sobject.enterprise.soap.sforce.com","OverLimitAction","http://www.w3.org/2001/XMLSchema","string",0,1,true), OverLimitAction, OverLimitAction__is_set);
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    protected void setSystemModstamp(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldSystemModstamp(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), SystemModstamp, SystemModstamp__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "EmailServicesFunction");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[EmailServicesFunction ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAddressInactiveAction(__out, __typeMapper);
      writeFieldAddresses(__out, __typeMapper);
      writeFieldApexClassId(__out, __typeMapper);
      writeFieldAttachmentOption(__out, __typeMapper);
      writeFieldAuthenticationFailureAction(__out, __typeMapper);
      writeFieldAuthorizationFailureAction(__out, __typeMapper);
      writeFieldAuthorizedSenders(__out, __typeMapper);
      writeFieldCreatedBy(__out, __typeMapper);
      writeFieldCreatedById(__out, __typeMapper);
      writeFieldCreatedDate(__out, __typeMapper);
      writeFieldErrorRoutingAddress(__out, __typeMapper);
      writeFieldFunctionInactiveAction(__out, __typeMapper);
      writeFieldFunctionName(__out, __typeMapper);
      writeFieldIsActive(__out, __typeMapper);
      writeFieldIsAuthenticationRequired(__out, __typeMapper);
      writeFieldIsErrorRoutingEnabled(__out, __typeMapper);
      writeFieldIsTextAttachmentsAsBinary(__out, __typeMapper);
      writeFieldIsTlsRequired(__out, __typeMapper);
      writeFieldLastModifiedBy(__out, __typeMapper);
      writeFieldLastModifiedById(__out, __typeMapper);
      writeFieldLastModifiedDate(__out, __typeMapper);
      writeFieldOverLimitAction(__out, __typeMapper);
      writeFieldSystemModstamp(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAddressInactiveAction(__in, __typeMapper);
      setAddresses(__in, __typeMapper);
      setApexClassId(__in, __typeMapper);
      setAttachmentOption(__in, __typeMapper);
      setAuthenticationFailureAction(__in, __typeMapper);
      setAuthorizationFailureAction(__in, __typeMapper);
      setAuthorizedSenders(__in, __typeMapper);
      setCreatedBy(__in, __typeMapper);
      setCreatedById(__in, __typeMapper);
      setCreatedDate(__in, __typeMapper);
      setErrorRoutingAddress(__in, __typeMapper);
      setFunctionInactiveAction(__in, __typeMapper);
      setFunctionName(__in, __typeMapper);
      setIsActive(__in, __typeMapper);
      setIsAuthenticationRequired(__in, __typeMapper);
      setIsErrorRoutingEnabled(__in, __typeMapper);
      setIsTextAttachmentsAsBinary(__in, __typeMapper);
      setIsTlsRequired(__in, __typeMapper);
      setLastModifiedBy(__in, __typeMapper);
      setLastModifiedById(__in, __typeMapper);
      setLastModifiedDate(__in, __typeMapper);
      setOverLimitAction(__in, __typeMapper);
      setSystemModstamp(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "AddressInactiveAction", AddressInactiveAction);
      toStringHelper(sb, "Addresses", Addresses);
      toStringHelper(sb, "ApexClassId", ApexClassId);
      toStringHelper(sb, "AttachmentOption", AttachmentOption);
      toStringHelper(sb, "AuthenticationFailureAction", AuthenticationFailureAction);
      toStringHelper(sb, "AuthorizationFailureAction", AuthorizationFailureAction);
      toStringHelper(sb, "AuthorizedSenders", AuthorizedSenders);
      toStringHelper(sb, "CreatedBy", CreatedBy);
      toStringHelper(sb, "CreatedById", CreatedById);
      toStringHelper(sb, "CreatedDate", CreatedDate);
      toStringHelper(sb, "ErrorRoutingAddress", ErrorRoutingAddress);
      toStringHelper(sb, "FunctionInactiveAction", FunctionInactiveAction);
      toStringHelper(sb, "FunctionName", FunctionName);
      toStringHelper(sb, "IsActive", IsActive);
      toStringHelper(sb, "IsAuthenticationRequired", IsAuthenticationRequired);
      toStringHelper(sb, "IsErrorRoutingEnabled", IsErrorRoutingEnabled);
      toStringHelper(sb, "IsTextAttachmentsAsBinary", IsTextAttachmentsAsBinary);
      toStringHelper(sb, "IsTlsRequired", IsTlsRequired);
      toStringHelper(sb, "LastModifiedBy", LastModifiedBy);
      toStringHelper(sb, "LastModifiedById", LastModifiedById);
      toStringHelper(sb, "LastModifiedDate", LastModifiedDate);
      toStringHelper(sb, "OverLimitAction", OverLimitAction);
      toStringHelper(sb, "SystemModstamp", SystemModstamp);
    }


}
