package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class PicklistValueInfo extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public PicklistValueInfo() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : DurableId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean DurableId__is_set = false;

    private java.lang.String DurableId;

    public java.lang.String getDurableId() {
      return DurableId;
    }

    public void setDurableId(java.lang.String DurableId) {
      this.DurableId = DurableId;
      DurableId__is_set = true;
    }

    protected void setDurableId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("DurableId", "urn:sobject.enterprise.soap.sforce.com","DurableId","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setDurableId(__typeMapper.readString(__in, _lookupTypeInfo("DurableId", "urn:sobject.enterprise.soap.sforce.com","DurableId","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldDurableId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("DurableId", "urn:sobject.enterprise.soap.sforce.com","DurableId","http://www.w3.org/2001/XMLSchema","string",0,1,true), DurableId, DurableId__is_set);
    }

    /**
     * element : EntityParticle of type {urn:sobject.enterprise.soap.sforce.com}EntityParticle
     * java type: com.sforce.soap.enterprise.sobject.EntityParticle
     */
    private boolean EntityParticle__is_set = false;

    private com.sforce.soap.enterprise.sobject.EntityParticle EntityParticle;

    public com.sforce.soap.enterprise.sobject.EntityParticle getEntityParticle() {
      return EntityParticle;
    }

    public void setEntityParticle(com.sforce.soap.enterprise.sobject.EntityParticle EntityParticle) {
      this.EntityParticle = EntityParticle;
      EntityParticle__is_set = true;
    }

    protected void setEntityParticle(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("EntityParticle", "urn:sobject.enterprise.soap.sforce.com","EntityParticle","urn:sobject.enterprise.soap.sforce.com","EntityParticle",0,1,true))) {
        setEntityParticle((com.sforce.soap.enterprise.sobject.EntityParticle)__typeMapper.readObject(__in, _lookupTypeInfo("EntityParticle", "urn:sobject.enterprise.soap.sforce.com","EntityParticle","urn:sobject.enterprise.soap.sforce.com","EntityParticle",0,1,true), com.sforce.soap.enterprise.sobject.EntityParticle.class));
      }
    }

    private void writeFieldEntityParticle(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("EntityParticle", "urn:sobject.enterprise.soap.sforce.com","EntityParticle","urn:sobject.enterprise.soap.sforce.com","EntityParticle",0,1,true), EntityParticle, EntityParticle__is_set);
    }

    /**
     * element : EntityParticleId of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean EntityParticleId__is_set = false;

    private java.lang.String EntityParticleId;

    public java.lang.String getEntityParticleId() {
      return EntityParticleId;
    }

    public void setEntityParticleId(java.lang.String EntityParticleId) {
      this.EntityParticleId = EntityParticleId;
      EntityParticleId__is_set = true;
    }

    protected void setEntityParticleId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("EntityParticleId", "urn:sobject.enterprise.soap.sforce.com","EntityParticleId","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setEntityParticleId(__typeMapper.readString(__in, _lookupTypeInfo("EntityParticleId", "urn:sobject.enterprise.soap.sforce.com","EntityParticleId","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldEntityParticleId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("EntityParticleId", "urn:sobject.enterprise.soap.sforce.com","EntityParticleId","http://www.w3.org/2001/XMLSchema","string",0,1,true), EntityParticleId, EntityParticleId__is_set);
    }

    /**
     * element : IsActive of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsActive__is_set = false;

    private java.lang.Boolean IsActive;

    public java.lang.Boolean getIsActive() {
      return IsActive;
    }

    public void setIsActive(java.lang.Boolean IsActive) {
      this.IsActive = IsActive;
      IsActive__is_set = true;
    }

    protected void setIsActive(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsActive((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsActive(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsActive", "urn:sobject.enterprise.soap.sforce.com","IsActive","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsActive, IsActive__is_set);
    }

    /**
     * element : IsDefaultValue of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsDefaultValue__is_set = false;

    private java.lang.Boolean IsDefaultValue;

    public java.lang.Boolean getIsDefaultValue() {
      return IsDefaultValue;
    }

    public void setIsDefaultValue(java.lang.Boolean IsDefaultValue) {
      this.IsDefaultValue = IsDefaultValue;
      IsDefaultValue__is_set = true;
    }

    protected void setIsDefaultValue(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsDefaultValue", "urn:sobject.enterprise.soap.sforce.com","IsDefaultValue","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsDefaultValue((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsDefaultValue", "urn:sobject.enterprise.soap.sforce.com","IsDefaultValue","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsDefaultValue(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsDefaultValue", "urn:sobject.enterprise.soap.sforce.com","IsDefaultValue","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsDefaultValue, IsDefaultValue__is_set);
    }

    /**
     * element : Label of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Label__is_set = false;

    private java.lang.String Label;

    public java.lang.String getLabel() {
      return Label;
    }

    public void setLabel(java.lang.String Label) {
      this.Label = Label;
      Label__is_set = true;
    }

    protected void setLabel(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Label", "urn:sobject.enterprise.soap.sforce.com","Label","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setLabel(__typeMapper.readString(__in, _lookupTypeInfo("Label", "urn:sobject.enterprise.soap.sforce.com","Label","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLabel(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Label", "urn:sobject.enterprise.soap.sforce.com","Label","http://www.w3.org/2001/XMLSchema","string",0,1,true), Label, Label__is_set);
    }

    /**
     * element : ValidFor of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean ValidFor__is_set = false;

    private java.lang.String ValidFor;

    public java.lang.String getValidFor() {
      return ValidFor;
    }

    public void setValidFor(java.lang.String ValidFor) {
      this.ValidFor = ValidFor;
      ValidFor__is_set = true;
    }

    protected void setValidFor(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ValidFor", "urn:sobject.enterprise.soap.sforce.com","ValidFor","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setValidFor(__typeMapper.readString(__in, _lookupTypeInfo("ValidFor", "urn:sobject.enterprise.soap.sforce.com","ValidFor","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldValidFor(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ValidFor", "urn:sobject.enterprise.soap.sforce.com","ValidFor","http://www.w3.org/2001/XMLSchema","string",0,1,true), ValidFor, ValidFor__is_set);
    }

    /**
     * element : Value of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Value__is_set = false;

    private java.lang.String Value;

    public java.lang.String getValue() {
      return Value;
    }

    public void setValue(java.lang.String Value) {
      this.Value = Value;
      Value__is_set = true;
    }

    protected void setValue(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Value", "urn:sobject.enterprise.soap.sforce.com","Value","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setValue(__typeMapper.readString(__in, _lookupTypeInfo("Value", "urn:sobject.enterprise.soap.sforce.com","Value","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldValue(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Value", "urn:sobject.enterprise.soap.sforce.com","Value","http://www.w3.org/2001/XMLSchema","string",0,1,true), Value, Value__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "PicklistValueInfo");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[PicklistValueInfo ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldDurableId(__out, __typeMapper);
      writeFieldEntityParticle(__out, __typeMapper);
      writeFieldEntityParticleId(__out, __typeMapper);
      writeFieldIsActive(__out, __typeMapper);
      writeFieldIsDefaultValue(__out, __typeMapper);
      writeFieldLabel(__out, __typeMapper);
      writeFieldValidFor(__out, __typeMapper);
      writeFieldValue(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setDurableId(__in, __typeMapper);
      setEntityParticle(__in, __typeMapper);
      setEntityParticleId(__in, __typeMapper);
      setIsActive(__in, __typeMapper);
      setIsDefaultValue(__in, __typeMapper);
      setLabel(__in, __typeMapper);
      setValidFor(__in, __typeMapper);
      setValue(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "DurableId", DurableId);
      toStringHelper(sb, "EntityParticle", EntityParticle);
      toStringHelper(sb, "EntityParticleId", EntityParticleId);
      toStringHelper(sb, "IsActive", IsActive);
      toStringHelper(sb, "IsDefaultValue", IsDefaultValue);
      toStringHelper(sb, "Label", Label);
      toStringHelper(sb, "ValidFor", ValidFor);
      toStringHelper(sb, "Value", Value);
    }


}
