package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class Special_Cost__c extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public Special_Cost__c() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : Agile_Opportunity_ID__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Agile_Opportunity_ID__c__is_set = false;

    private java.lang.String Agile_Opportunity_ID__c;

    public java.lang.String getAgile_Opportunity_ID__c() {
      return Agile_Opportunity_ID__c;
    }

    public void setAgile_Opportunity_ID__c(java.lang.String Agile_Opportunity_ID__c) {
      this.Agile_Opportunity_ID__c = Agile_Opportunity_ID__c;
      Agile_Opportunity_ID__c__is_set = true;
    }

    protected void setAgile_Opportunity_ID__c(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Agile_Opportunity_ID__c", "urn:sobject.enterprise.soap.sforce.com","Agile_Opportunity_ID__c","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setAgile_Opportunity_ID__c(__typeMapper.readString(__in, _lookupTypeInfo("Agile_Opportunity_ID__c", "urn:sobject.enterprise.soap.sforce.com","Agile_Opportunity_ID__c","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAgile_Opportunity_ID__c(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Agile_Opportunity_ID__c", "urn:sobject.enterprise.soap.sforce.com","Agile_Opportunity_ID__c","http://www.w3.org/2001/XMLSchema","string",0,1,true), Agile_Opportunity_ID__c, Agile_Opportunity_ID__c__is_set);
    }

    /**
     * element : Cost__c of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private boolean Cost__c__is_set = false;

    private java.lang.Double Cost__c;

    public java.lang.Double getCost__c() {
      return Cost__c;
    }

    public void setCost__c(java.lang.Double Cost__c) {
      this.Cost__c = Cost__c;
      Cost__c__is_set = true;
    }

    protected void setCost__c(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Cost__c", "urn:sobject.enterprise.soap.sforce.com","Cost__c","http://www.w3.org/2001/XMLSchema","double",0,1,true))) {
        setCost__c((java.lang.Double)__typeMapper.readObject(__in, _lookupTypeInfo("Cost__c", "urn:sobject.enterprise.soap.sforce.com","Cost__c","http://www.w3.org/2001/XMLSchema","double",0,1,true), java.lang.Double.class));
      }
    }

    private void writeFieldCost__c(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Cost__c", "urn:sobject.enterprise.soap.sforce.com","Cost__c","http://www.w3.org/2001/XMLSchema","double",0,1,true), Cost__c, Cost__c__is_set);
    }

    /**
     * element : Name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Name__is_set = false;

    private java.lang.String Name;

    public java.lang.String getName() {
      return Name;
    }

    public void setName(java.lang.String Name) {
      this.Name = Name;
      Name__is_set = true;
    }

    protected void setName(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Name", "urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setName(__typeMapper.readString(__in, _lookupTypeInfo("Name", "urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Name", "urn:sobject.enterprise.soap.sforce.com","Name","http://www.w3.org/2001/XMLSchema","string",0,1,true), Name, Name__is_set);
    }

    /**
     * element : Product__c of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean Product__c__is_set = false;

    private java.lang.String Product__c;

    public java.lang.String getProduct__c() {
      return Product__c;
    }

    public void setProduct__c(java.lang.String Product__c) {
      this.Product__c = Product__c;
      Product__c__is_set = true;
    }

    protected void setProduct__c(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Product__c", "urn:sobject.enterprise.soap.sforce.com","Product__c","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setProduct__c(__typeMapper.readString(__in, _lookupTypeInfo("Product__c", "urn:sobject.enterprise.soap.sforce.com","Product__c","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldProduct__c(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Product__c", "urn:sobject.enterprise.soap.sforce.com","Product__c","urn:enterprise.soap.sforce.com","ID",0,1,true), Product__c, Product__c__is_set);
    }

    /**
     * element : Product_Description__c of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Product_Description__c__is_set = false;

    private java.lang.String Product_Description__c;

    public java.lang.String getProduct_Description__c() {
      return Product_Description__c;
    }

    public void setProduct_Description__c(java.lang.String Product_Description__c) {
      this.Product_Description__c = Product_Description__c;
      Product_Description__c__is_set = true;
    }

    protected void setProduct_Description__c(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Product_Description__c", "urn:sobject.enterprise.soap.sforce.com","Product_Description__c","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setProduct_Description__c(__typeMapper.readString(__in, _lookupTypeInfo("Product_Description__c", "urn:sobject.enterprise.soap.sforce.com","Product_Description__c","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldProduct_Description__c(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Product_Description__c", "urn:sobject.enterprise.soap.sforce.com","Product_Description__c","http://www.w3.org/2001/XMLSchema","string",0,1,true), Product_Description__c, Product_Description__c__is_set);
    }

    /**
     * element : Sales_Enablement_User_Lookup__c of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean Sales_Enablement_User_Lookup__c__is_set = false;

    private java.lang.String Sales_Enablement_User_Lookup__c;

    public java.lang.String getSales_Enablement_User_Lookup__c() {
      return Sales_Enablement_User_Lookup__c;
    }

    public void setSales_Enablement_User_Lookup__c(java.lang.String Sales_Enablement_User_Lookup__c) {
      this.Sales_Enablement_User_Lookup__c = Sales_Enablement_User_Lookup__c;
      Sales_Enablement_User_Lookup__c__is_set = true;
    }

    protected void setSales_Enablement_User_Lookup__c(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Sales_Enablement_User_Lookup__c", "urn:sobject.enterprise.soap.sforce.com","Sales_Enablement_User_Lookup__c","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setSales_Enablement_User_Lookup__c(__typeMapper.readString(__in, _lookupTypeInfo("Sales_Enablement_User_Lookup__c", "urn:sobject.enterprise.soap.sforce.com","Sales_Enablement_User_Lookup__c","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldSales_Enablement_User_Lookup__c(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Sales_Enablement_User_Lookup__c", "urn:sobject.enterprise.soap.sforce.com","Sales_Enablement_User_Lookup__c","urn:enterprise.soap.sforce.com","ID",0,1,true), Sales_Enablement_User_Lookup__c, Sales_Enablement_User_Lookup__c__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "Special_Cost__c");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Special_Cost__c ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAgile_Opportunity_ID__c(__out, __typeMapper);
      writeFieldCost__c(__out, __typeMapper);
      writeFieldName(__out, __typeMapper);
      writeFieldProduct__c(__out, __typeMapper);
      writeFieldProduct_Description__c(__out, __typeMapper);
      writeFieldSales_Enablement_User_Lookup__c(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAgile_Opportunity_ID__c(__in, __typeMapper);
      setCost__c(__in, __typeMapper);
      setName(__in, __typeMapper);
      setProduct__c(__in, __typeMapper);
      setProduct_Description__c(__in, __typeMapper);
      setSales_Enablement_User_Lookup__c(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "Agile_Opportunity_ID__c", Agile_Opportunity_ID__c);
      toStringHelper(sb, "Cost__c", Cost__c);
      toStringHelper(sb, "Name", Name);
      toStringHelper(sb, "Product__c", Product__c);
      toStringHelper(sb, "Product_Description__c", Product_Description__c);
      toStringHelper(sb, "Sales_Enablement_User_Lookup__c", Sales_Enablement_User_Lookup__c);
    }


}
