package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class VerificationHistory extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public VerificationHistory() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : Activity of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Activity__is_set = false;

    private java.lang.String Activity;

    public java.lang.String getActivity() {
      return Activity;
    }

    public void setActivity(java.lang.String Activity) {
      this.Activity = Activity;
      Activity__is_set = true;
    }

    protected void setActivity(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Activity", "urn:sobject.enterprise.soap.sforce.com","Activity","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setActivity(__typeMapper.readString(__in, _lookupTypeInfo("Activity", "urn:sobject.enterprise.soap.sforce.com","Activity","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldActivity(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Activity", "urn:sobject.enterprise.soap.sforce.com","Activity","http://www.w3.org/2001/XMLSchema","string",0,1,true), Activity, Activity__is_set);
    }

    /**
     * element : CreatedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean CreatedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User CreatedBy;

    public com.sforce.soap.enterprise.sobject.User getCreatedBy() {
      return CreatedBy;
    }

    public void setCreatedBy(com.sforce.soap.enterprise.sobject.User CreatedBy) {
      this.CreatedBy = CreatedBy;
      CreatedBy__is_set = true;
    }

    protected void setCreatedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setCreatedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldCreatedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedBy", "urn:sobject.enterprise.soap.sforce.com","CreatedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), CreatedBy, CreatedBy__is_set);
    }

    /**
     * element : CreatedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean CreatedById__is_set = false;

    private java.lang.String CreatedById;

    public java.lang.String getCreatedById() {
      return CreatedById;
    }

    public void setCreatedById(java.lang.String CreatedById) {
      this.CreatedById = CreatedById;
      CreatedById__is_set = true;
    }

    protected void setCreatedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setCreatedById(__typeMapper.readString(__in, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldCreatedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedById", "urn:sobject.enterprise.soap.sforce.com","CreatedById","urn:enterprise.soap.sforce.com","ID",0,1,true), CreatedById, CreatedById__is_set);
    }

    /**
     * element : CreatedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean CreatedDate__is_set = false;

    private java.util.Calendar CreatedDate;

    public java.util.Calendar getCreatedDate() {
      return CreatedDate;
    }

    public void setCreatedDate(java.util.Calendar CreatedDate) {
      this.CreatedDate = CreatedDate;
      CreatedDate__is_set = true;
    }

    protected void setCreatedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setCreatedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldCreatedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("CreatedDate", "urn:sobject.enterprise.soap.sforce.com","CreatedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), CreatedDate, CreatedDate__is_set);
    }

    /**
     * element : EventGroup of type {http://www.w3.org/2001/XMLSchema}int
     * java type: java.lang.Integer
     */
    private boolean EventGroup__is_set = false;

    private java.lang.Integer EventGroup;

    public java.lang.Integer getEventGroup() {
      return EventGroup;
    }

    public void setEventGroup(java.lang.Integer EventGroup) {
      this.EventGroup = EventGroup;
      EventGroup__is_set = true;
    }

    protected void setEventGroup(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("EventGroup", "urn:sobject.enterprise.soap.sforce.com","EventGroup","http://www.w3.org/2001/XMLSchema","int",0,1,true))) {
        setEventGroup((java.lang.Integer)__typeMapper.readObject(__in, _lookupTypeInfo("EventGroup", "urn:sobject.enterprise.soap.sforce.com","EventGroup","http://www.w3.org/2001/XMLSchema","int",0,1,true), java.lang.Integer.class));
      }
    }

    private void writeFieldEventGroup(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("EventGroup", "urn:sobject.enterprise.soap.sforce.com","EventGroup","http://www.w3.org/2001/XMLSchema","int",0,1,true), EventGroup, EventGroup__is_set);
    }

    /**
     * element : IsDeleted of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean IsDeleted__is_set = false;

    private java.lang.Boolean IsDeleted;

    public java.lang.Boolean getIsDeleted() {
      return IsDeleted;
    }

    public void setIsDeleted(java.lang.Boolean IsDeleted) {
      this.IsDeleted = IsDeleted;
      IsDeleted__is_set = true;
    }

    protected void setIsDeleted(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("IsDeleted", "urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true))) {
        setIsDeleted((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("IsDeleted", "urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldIsDeleted(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("IsDeleted", "urn:sobject.enterprise.soap.sforce.com","IsDeleted","http://www.w3.org/2001/XMLSchema","boolean",0,1,true), IsDeleted, IsDeleted__is_set);
    }

    /**
     * element : LastModifiedBy of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean LastModifiedBy__is_set = false;

    private com.sforce.soap.enterprise.sobject.User LastModifiedBy;

    public com.sforce.soap.enterprise.sobject.User getLastModifiedBy() {
      return LastModifiedBy;
    }

    public void setLastModifiedBy(com.sforce.soap.enterprise.sobject.User LastModifiedBy) {
      this.LastModifiedBy = LastModifiedBy;
      LastModifiedBy__is_set = true;
    }

    protected void setLastModifiedBy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setLastModifiedBy((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldLastModifiedBy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedBy", "urn:sobject.enterprise.soap.sforce.com","LastModifiedBy","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), LastModifiedBy, LastModifiedBy__is_set);
    }

    /**
     * element : LastModifiedById of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LastModifiedById__is_set = false;

    private java.lang.String LastModifiedById;

    public java.lang.String getLastModifiedById() {
      return LastModifiedById;
    }

    public void setLastModifiedById(java.lang.String LastModifiedById) {
      this.LastModifiedById = LastModifiedById;
      LastModifiedById__is_set = true;
    }

    protected void setLastModifiedById(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setLastModifiedById(__typeMapper.readString(__in, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLastModifiedById(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedById", "urn:sobject.enterprise.soap.sforce.com","LastModifiedById","urn:enterprise.soap.sforce.com","ID",0,1,true), LastModifiedById, LastModifiedById__is_set);
    }

    /**
     * element : LastModifiedDate of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean LastModifiedDate__is_set = false;

    private java.util.Calendar LastModifiedDate;

    public java.util.Calendar getLastModifiedDate() {
      return LastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Calendar LastModifiedDate) {
      this.LastModifiedDate = LastModifiedDate;
      LastModifiedDate__is_set = true;
    }

    protected void setLastModifiedDate(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setLastModifiedDate((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldLastModifiedDate(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LastModifiedDate", "urn:sobject.enterprise.soap.sforce.com","LastModifiedDate","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), LastModifiedDate, LastModifiedDate__is_set);
    }

    /**
     * element : LoginGeo of type {urn:sobject.enterprise.soap.sforce.com}LoginGeo
     * java type: com.sforce.soap.enterprise.sobject.LoginGeo
     */
    private boolean LoginGeo__is_set = false;

    private com.sforce.soap.enterprise.sobject.LoginGeo LoginGeo;

    public com.sforce.soap.enterprise.sobject.LoginGeo getLoginGeo() {
      return LoginGeo;
    }

    public void setLoginGeo(com.sforce.soap.enterprise.sobject.LoginGeo LoginGeo) {
      this.LoginGeo = LoginGeo;
      LoginGeo__is_set = true;
    }

    protected void setLoginGeo(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LoginGeo", "urn:sobject.enterprise.soap.sforce.com","LoginGeo","urn:sobject.enterprise.soap.sforce.com","LoginGeo",0,1,true))) {
        setLoginGeo((com.sforce.soap.enterprise.sobject.LoginGeo)__typeMapper.readObject(__in, _lookupTypeInfo("LoginGeo", "urn:sobject.enterprise.soap.sforce.com","LoginGeo","urn:sobject.enterprise.soap.sforce.com","LoginGeo",0,1,true), com.sforce.soap.enterprise.sobject.LoginGeo.class));
      }
    }

    private void writeFieldLoginGeo(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LoginGeo", "urn:sobject.enterprise.soap.sforce.com","LoginGeo","urn:sobject.enterprise.soap.sforce.com","LoginGeo",0,1,true), LoginGeo, LoginGeo__is_set);
    }

    /**
     * element : LoginGeoId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LoginGeoId__is_set = false;

    private java.lang.String LoginGeoId;

    public java.lang.String getLoginGeoId() {
      return LoginGeoId;
    }

    public void setLoginGeoId(java.lang.String LoginGeoId) {
      this.LoginGeoId = LoginGeoId;
      LoginGeoId__is_set = true;
    }

    protected void setLoginGeoId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LoginGeoId", "urn:sobject.enterprise.soap.sforce.com","LoginGeoId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setLoginGeoId(__typeMapper.readString(__in, _lookupTypeInfo("LoginGeoId", "urn:sobject.enterprise.soap.sforce.com","LoginGeoId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLoginGeoId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LoginGeoId", "urn:sobject.enterprise.soap.sforce.com","LoginGeoId","urn:enterprise.soap.sforce.com","ID",0,1,true), LoginGeoId, LoginGeoId__is_set);
    }

    /**
     * element : LoginHistory of type {urn:sobject.enterprise.soap.sforce.com}LoginHistory
     * java type: com.sforce.soap.enterprise.sobject.LoginHistory
     */
    private boolean LoginHistory__is_set = false;

    private com.sforce.soap.enterprise.sobject.LoginHistory LoginHistory;

    public com.sforce.soap.enterprise.sobject.LoginHistory getLoginHistory() {
      return LoginHistory;
    }

    public void setLoginHistory(com.sforce.soap.enterprise.sobject.LoginHistory LoginHistory) {
      this.LoginHistory = LoginHistory;
      LoginHistory__is_set = true;
    }

    protected void setLoginHistory(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LoginHistory", "urn:sobject.enterprise.soap.sforce.com","LoginHistory","urn:sobject.enterprise.soap.sforce.com","LoginHistory",0,1,true))) {
        setLoginHistory((com.sforce.soap.enterprise.sobject.LoginHistory)__typeMapper.readObject(__in, _lookupTypeInfo("LoginHistory", "urn:sobject.enterprise.soap.sforce.com","LoginHistory","urn:sobject.enterprise.soap.sforce.com","LoginHistory",0,1,true), com.sforce.soap.enterprise.sobject.LoginHistory.class));
      }
    }

    private void writeFieldLoginHistory(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LoginHistory", "urn:sobject.enterprise.soap.sforce.com","LoginHistory","urn:sobject.enterprise.soap.sforce.com","LoginHistory",0,1,true), LoginHistory, LoginHistory__is_set);
    }

    /**
     * element : LoginHistoryId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean LoginHistoryId__is_set = false;

    private java.lang.String LoginHistoryId;

    public java.lang.String getLoginHistoryId() {
      return LoginHistoryId;
    }

    public void setLoginHistoryId(java.lang.String LoginHistoryId) {
      this.LoginHistoryId = LoginHistoryId;
      LoginHistoryId__is_set = true;
    }

    protected void setLoginHistoryId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("LoginHistoryId", "urn:sobject.enterprise.soap.sforce.com","LoginHistoryId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setLoginHistoryId(__typeMapper.readString(__in, _lookupTypeInfo("LoginHistoryId", "urn:sobject.enterprise.soap.sforce.com","LoginHistoryId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldLoginHistoryId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("LoginHistoryId", "urn:sobject.enterprise.soap.sforce.com","LoginHistoryId","urn:enterprise.soap.sforce.com","ID",0,1,true), LoginHistoryId, LoginHistoryId__is_set);
    }

    /**
     * element : Policy of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Policy__is_set = false;

    private java.lang.String Policy;

    public java.lang.String getPolicy() {
      return Policy;
    }

    public void setPolicy(java.lang.String Policy) {
      this.Policy = Policy;
      Policy__is_set = true;
    }

    protected void setPolicy(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Policy", "urn:sobject.enterprise.soap.sforce.com","Policy","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setPolicy(__typeMapper.readString(__in, _lookupTypeInfo("Policy", "urn:sobject.enterprise.soap.sforce.com","Policy","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldPolicy(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Policy", "urn:sobject.enterprise.soap.sforce.com","Policy","http://www.w3.org/2001/XMLSchema","string",0,1,true), Policy, Policy__is_set);
    }

    /**
     * element : Remarks of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Remarks__is_set = false;

    private java.lang.String Remarks;

    public java.lang.String getRemarks() {
      return Remarks;
    }

    public void setRemarks(java.lang.String Remarks) {
      this.Remarks = Remarks;
      Remarks__is_set = true;
    }

    protected void setRemarks(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Remarks", "urn:sobject.enterprise.soap.sforce.com","Remarks","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setRemarks(__typeMapper.readString(__in, _lookupTypeInfo("Remarks", "urn:sobject.enterprise.soap.sforce.com","Remarks","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldRemarks(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Remarks", "urn:sobject.enterprise.soap.sforce.com","Remarks","http://www.w3.org/2001/XMLSchema","string",0,1,true), Remarks, Remarks__is_set);
    }

    /**
     * element : Resource of type {urn:sobject.enterprise.soap.sforce.com}ConnectedApplication
     * java type: com.sforce.soap.enterprise.sobject.ConnectedApplication
     */
    private boolean Resource__is_set = false;

    private com.sforce.soap.enterprise.sobject.ConnectedApplication Resource;

    public com.sforce.soap.enterprise.sobject.ConnectedApplication getResource() {
      return Resource;
    }

    public void setResource(com.sforce.soap.enterprise.sobject.ConnectedApplication Resource) {
      this.Resource = Resource;
      Resource__is_set = true;
    }

    protected void setResource(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Resource", "urn:sobject.enterprise.soap.sforce.com","Resource","urn:sobject.enterprise.soap.sforce.com","ConnectedApplication",0,1,true))) {
        setResource((com.sforce.soap.enterprise.sobject.ConnectedApplication)__typeMapper.readObject(__in, _lookupTypeInfo("Resource", "urn:sobject.enterprise.soap.sforce.com","Resource","urn:sobject.enterprise.soap.sforce.com","ConnectedApplication",0,1,true), com.sforce.soap.enterprise.sobject.ConnectedApplication.class));
      }
    }

    private void writeFieldResource(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Resource", "urn:sobject.enterprise.soap.sforce.com","Resource","urn:sobject.enterprise.soap.sforce.com","ConnectedApplication",0,1,true), Resource, Resource__is_set);
    }

    /**
     * element : ResourceId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean ResourceId__is_set = false;

    private java.lang.String ResourceId;

    public java.lang.String getResourceId() {
      return ResourceId;
    }

    public void setResourceId(java.lang.String ResourceId) {
      this.ResourceId = ResourceId;
      ResourceId__is_set = true;
    }

    protected void setResourceId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("ResourceId", "urn:sobject.enterprise.soap.sforce.com","ResourceId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setResourceId(__typeMapper.readString(__in, _lookupTypeInfo("ResourceId", "urn:sobject.enterprise.soap.sforce.com","ResourceId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldResourceId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("ResourceId", "urn:sobject.enterprise.soap.sforce.com","ResourceId","urn:enterprise.soap.sforce.com","ID",0,1,true), ResourceId, ResourceId__is_set);
    }

    /**
     * element : SourceIp of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean SourceIp__is_set = false;

    private java.lang.String SourceIp;

    public java.lang.String getSourceIp() {
      return SourceIp;
    }

    public void setSourceIp(java.lang.String SourceIp) {
      this.SourceIp = SourceIp;
      SourceIp__is_set = true;
    }

    protected void setSourceIp(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("SourceIp", "urn:sobject.enterprise.soap.sforce.com","SourceIp","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setSourceIp(__typeMapper.readString(__in, _lookupTypeInfo("SourceIp", "urn:sobject.enterprise.soap.sforce.com","SourceIp","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldSourceIp(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("SourceIp", "urn:sobject.enterprise.soap.sforce.com","SourceIp","http://www.w3.org/2001/XMLSchema","string",0,1,true), SourceIp, SourceIp__is_set);
    }

    /**
     * element : Status of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean Status__is_set = false;

    private java.lang.String Status;

    public java.lang.String getStatus() {
      return Status;
    }

    public void setStatus(java.lang.String Status) {
      this.Status = Status;
      Status__is_set = true;
    }

    protected void setStatus(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("Status", "urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setStatus(__typeMapper.readString(__in, _lookupTypeInfo("Status", "urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldStatus(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("Status", "urn:sobject.enterprise.soap.sforce.com","Status","http://www.w3.org/2001/XMLSchema","string",0,1,true), Status, Status__is_set);
    }

    /**
     * element : SystemModstamp of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean SystemModstamp__is_set = false;

    private java.util.Calendar SystemModstamp;

    public java.util.Calendar getSystemModstamp() {
      return SystemModstamp;
    }

    public void setSystemModstamp(java.util.Calendar SystemModstamp) {
      this.SystemModstamp = SystemModstamp;
      SystemModstamp__is_set = true;
    }

    protected void setSystemModstamp(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setSystemModstamp((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldSystemModstamp(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("SystemModstamp", "urn:sobject.enterprise.soap.sforce.com","SystemModstamp","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), SystemModstamp, SystemModstamp__is_set);
    }

    /**
     * element : User of type {urn:sobject.enterprise.soap.sforce.com}User
     * java type: com.sforce.soap.enterprise.sobject.User
     */
    private boolean User__is_set = false;

    private com.sforce.soap.enterprise.sobject.User User;

    public com.sforce.soap.enterprise.sobject.User getUser() {
      return User;
    }

    public void setUser(com.sforce.soap.enterprise.sobject.User User) {
      this.User = User;
      User__is_set = true;
    }

    protected void setUser(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("User", "urn:sobject.enterprise.soap.sforce.com","User","urn:sobject.enterprise.soap.sforce.com","User",0,1,true))) {
        setUser((com.sforce.soap.enterprise.sobject.User)__typeMapper.readObject(__in, _lookupTypeInfo("User", "urn:sobject.enterprise.soap.sforce.com","User","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), com.sforce.soap.enterprise.sobject.User.class));
      }
    }

    private void writeFieldUser(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("User", "urn:sobject.enterprise.soap.sforce.com","User","urn:sobject.enterprise.soap.sforce.com","User",0,1,true), User, User__is_set);
    }

    /**
     * element : UserId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean UserId__is_set = false;

    private java.lang.String UserId;

    public java.lang.String getUserId() {
      return UserId;
    }

    public void setUserId(java.lang.String UserId) {
      this.UserId = UserId;
      UserId__is_set = true;
    }

    protected void setUserId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("UserId", "urn:sobject.enterprise.soap.sforce.com","UserId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
        setUserId(__typeMapper.readString(__in, _lookupTypeInfo("UserId", "urn:sobject.enterprise.soap.sforce.com","UserId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldUserId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("UserId", "urn:sobject.enterprise.soap.sforce.com","UserId","urn:enterprise.soap.sforce.com","ID",0,1,true), UserId, UserId__is_set);
    }

    /**
     * element : VerificationMethod of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean VerificationMethod__is_set = false;

    private java.lang.String VerificationMethod;

    public java.lang.String getVerificationMethod() {
      return VerificationMethod;
    }

    public void setVerificationMethod(java.lang.String VerificationMethod) {
      this.VerificationMethod = VerificationMethod;
      VerificationMethod__is_set = true;
    }

    protected void setVerificationMethod(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("VerificationMethod", "urn:sobject.enterprise.soap.sforce.com","VerificationMethod","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
        setVerificationMethod(__typeMapper.readString(__in, _lookupTypeInfo("VerificationMethod", "urn:sobject.enterprise.soap.sforce.com","VerificationMethod","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
      }
    }

    private void writeFieldVerificationMethod(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("VerificationMethod", "urn:sobject.enterprise.soap.sforce.com","VerificationMethod","http://www.w3.org/2001/XMLSchema","string",0,1,true), VerificationMethod, VerificationMethod__is_set);
    }

    /**
     * element : VerificationTime of type {http://www.w3.org/2001/XMLSchema}dateTime
     * java type: java.util.Calendar
     */
    private boolean VerificationTime__is_set = false;

    private java.util.Calendar VerificationTime;

    public java.util.Calendar getVerificationTime() {
      return VerificationTime;
    }

    public void setVerificationTime(java.util.Calendar VerificationTime) {
      this.VerificationTime = VerificationTime;
      VerificationTime__is_set = true;
    }

    protected void setVerificationTime(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("VerificationTime", "urn:sobject.enterprise.soap.sforce.com","VerificationTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true))) {
        setVerificationTime((java.util.Calendar)__typeMapper.readObject(__in, _lookupTypeInfo("VerificationTime", "urn:sobject.enterprise.soap.sforce.com","VerificationTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), java.util.Calendar.class));
      }
    }

    private void writeFieldVerificationTime(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("VerificationTime", "urn:sobject.enterprise.soap.sforce.com","VerificationTime","http://www.w3.org/2001/XMLSchema","dateTime",0,1,true), VerificationTime, VerificationTime__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      __typeMapper.writeXsiType(__out, "urn:sobject.enterprise.soap.sforce.com", "VerificationHistory");
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[VerificationHistory ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldActivity(__out, __typeMapper);
      writeFieldCreatedBy(__out, __typeMapper);
      writeFieldCreatedById(__out, __typeMapper);
      writeFieldCreatedDate(__out, __typeMapper);
      writeFieldEventGroup(__out, __typeMapper);
      writeFieldIsDeleted(__out, __typeMapper);
      writeFieldLastModifiedBy(__out, __typeMapper);
      writeFieldLastModifiedById(__out, __typeMapper);
      writeFieldLastModifiedDate(__out, __typeMapper);
      writeFieldLoginGeo(__out, __typeMapper);
      writeFieldLoginGeoId(__out, __typeMapper);
      writeFieldLoginHistory(__out, __typeMapper);
      writeFieldLoginHistoryId(__out, __typeMapper);
      writeFieldPolicy(__out, __typeMapper);
      writeFieldRemarks(__out, __typeMapper);
      writeFieldResource(__out, __typeMapper);
      writeFieldResourceId(__out, __typeMapper);
      writeFieldSourceIp(__out, __typeMapper);
      writeFieldStatus(__out, __typeMapper);
      writeFieldSystemModstamp(__out, __typeMapper);
      writeFieldUser(__out, __typeMapper);
      writeFieldUserId(__out, __typeMapper);
      writeFieldVerificationMethod(__out, __typeMapper);
      writeFieldVerificationTime(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setActivity(__in, __typeMapper);
      setCreatedBy(__in, __typeMapper);
      setCreatedById(__in, __typeMapper);
      setCreatedDate(__in, __typeMapper);
      setEventGroup(__in, __typeMapper);
      setIsDeleted(__in, __typeMapper);
      setLastModifiedBy(__in, __typeMapper);
      setLastModifiedById(__in, __typeMapper);
      setLastModifiedDate(__in, __typeMapper);
      setLoginGeo(__in, __typeMapper);
      setLoginGeoId(__in, __typeMapper);
      setLoginHistory(__in, __typeMapper);
      setLoginHistoryId(__in, __typeMapper);
      setPolicy(__in, __typeMapper);
      setRemarks(__in, __typeMapper);
      setResource(__in, __typeMapper);
      setResourceId(__in, __typeMapper);
      setSourceIp(__in, __typeMapper);
      setStatus(__in, __typeMapper);
      setSystemModstamp(__in, __typeMapper);
      setUser(__in, __typeMapper);
      setUserId(__in, __typeMapper);
      setVerificationMethod(__in, __typeMapper);
      setVerificationTime(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "Activity", Activity);
      toStringHelper(sb, "CreatedBy", CreatedBy);
      toStringHelper(sb, "CreatedById", CreatedById);
      toStringHelper(sb, "CreatedDate", CreatedDate);
      toStringHelper(sb, "EventGroup", EventGroup);
      toStringHelper(sb, "IsDeleted", IsDeleted);
      toStringHelper(sb, "LastModifiedBy", LastModifiedBy);
      toStringHelper(sb, "LastModifiedById", LastModifiedById);
      toStringHelper(sb, "LastModifiedDate", LastModifiedDate);
      toStringHelper(sb, "LoginGeo", LoginGeo);
      toStringHelper(sb, "LoginGeoId", LoginGeoId);
      toStringHelper(sb, "LoginHistory", LoginHistory);
      toStringHelper(sb, "LoginHistoryId", LoginHistoryId);
      toStringHelper(sb, "Policy", Policy);
      toStringHelper(sb, "Remarks", Remarks);
      toStringHelper(sb, "Resource", Resource);
      toStringHelper(sb, "ResourceId", ResourceId);
      toStringHelper(sb, "SourceIp", SourceIp);
      toStringHelper(sb, "Status", Status);
      toStringHelper(sb, "SystemModstamp", SystemModstamp);
      toStringHelper(sb, "User", User);
      toStringHelper(sb, "UserId", UserId);
      toStringHelper(sb, "VerificationMethod", VerificationMethod);
      toStringHelper(sb, "VerificationTime", VerificationTime);
    }


}
