
package com.agile.ws.service.search.v1.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.agile.ws.schema.search.v1.jaxws.AdvancedSearchRequestType;
import com.agile.ws.schema.search.v1.jaxws.AdvancedSearchResponseType;
import com.agile.ws.schema.search.v1.jaxws.CreateQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.CreateQueryResponseType;
import com.agile.ws.schema.search.v1.jaxws.DeleteQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.DeleteQueryResponseType;
import com.agile.ws.schema.search.v1.jaxws.ExecuteSavedQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.ExecuteSavedQueryResponseType;
import com.agile.ws.schema.search.v1.jaxws.GetSearchableClassesRequestType;
import com.agile.ws.schema.search.v1.jaxws.GetSearchableClassesResponseType;
import com.agile.ws.schema.search.v1.jaxws.LoadQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.LoadQueryResponseType;
import com.agile.ws.schema.search.v1.jaxws.QueryGetSearchableAttributesRequestType;
import com.agile.ws.schema.search.v1.jaxws.QueryGetSearchableAttributesResponseType;
import com.agile.ws.schema.search.v1.jaxws.QuickSearchRequestType;
import com.agile.ws.schema.search.v1.jaxws.QuickSearchResponseType;
import com.agile.ws.schema.search.v1.jaxws.SaveAsQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.SaveAsQueryResponseType;
import com.agile.ws.schema.search.v1.jaxws.UpdateQueryRequestType;
import com.agile.ws.schema.search.v1.jaxws.UpdateQueryResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchService", targetNamespace = "http://xmlns.oracle.com/AgileServices/Core/Search/V1")
@XmlSeeAlso({
    com.agile.ws.schema.common.v1.jaxws.ObjectFactory.class,
    com.agile.ws.schema.search.v1.jaxws.ObjectFactory.class
})
public interface SearchService {


    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.QuickSearchResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "quickSearch", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.QuickSearch")
    @ResponseWrapper(localName = "quickSearchResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.QuickSearchResponse")
    public QuickSearchResponseType quickSearch(
        @WebParam(name = "request", targetNamespace = "")
        QuickSearchRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.AdvancedSearchResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "advancedSearch", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.AdvancedSearch")
    @ResponseWrapper(localName = "advancedSearchResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.AdvancedSearchResponse")
    public AdvancedSearchResponseType advancedSearch(
        @WebParam(name = "request", targetNamespace = "")
        AdvancedSearchRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.QueryGetSearchableAttributesResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getSearchableAttributes", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.GetSearchableAttributes")
    @ResponseWrapper(localName = "getSearchableAttributesResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.GetSearchableAttributesResponse")
    public QueryGetSearchableAttributesResponseType getSearchableAttributes(
        @WebParam(name = "request", targetNamespace = "")
        QueryGetSearchableAttributesRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.GetSearchableClassesResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getSearchableClasses", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.GetSearchableClasses")
    @ResponseWrapper(localName = "getSearchableClassesResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.GetSearchableClassesResponse")
    public GetSearchableClassesResponseType getSearchableClasses(
        @WebParam(name = "request", targetNamespace = "")
        GetSearchableClassesRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.CreateQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "createQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.CreateQuery")
    @ResponseWrapper(localName = "createQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.CreateQueryResponse")
    public CreateQueryResponseType createQuery(
        @WebParam(name = "request", targetNamespace = "")
        CreateQueryRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.LoadQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "loadQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.LoadQuery")
    @ResponseWrapper(localName = "loadQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.LoadQueryResponse")
    public LoadQueryResponseType loadQuery(
        @WebParam(name = "request", targetNamespace = "")
        LoadQueryRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.ExecuteSavedQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "executeSavedQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.ExecuteSavedQuery")
    @ResponseWrapper(localName = "executeSavedQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.ExecuteSavedQueryResponse")
    public ExecuteSavedQueryResponseType executeSavedQuery(
        @WebParam(name = "request", targetNamespace = "")
        ExecuteSavedQueryRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.SaveAsQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "saveAsQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.SaveAsQuery")
    @ResponseWrapper(localName = "saveAsQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.SaveAsQueryResponse")
    public SaveAsQueryResponseType saveAsQuery(
        @WebParam(name = "request", targetNamespace = "")
        SaveAsQueryRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.UpdateQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "updateQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.UpdateQuery")
    @ResponseWrapper(localName = "updateQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.UpdateQueryResponse")
    public UpdateQueryResponseType updateQuery(
        @WebParam(name = "request", targetNamespace = "")
        UpdateQueryRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.search.v1.jaxws.DeleteQueryResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "deleteQuery", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.DeleteQuery")
    @ResponseWrapper(localName = "deleteQueryResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Search/V1", className = "com.agile.ws.schema.search.v1.jaxws.DeleteQueryResponse")
    public DeleteQueryResponseType deleteQuery(
        @WebParam(name = "request", targetNamespace = "")
        DeleteQueryRequestType request);

}
