
package com.agile.ws.service.attachment.v1.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.agile.ws.schema.attachment.v1.jaxws.AddFileAttachmentRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.AddFileAttachmentResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.AddFileFFRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.AddFileFFResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.CancelCheckOutFFRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.CancelCheckOutFFResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckInAttachmentRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckInAttachmentResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckInFFRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckInFFResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckOutAttachmentRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckOutAttachmentResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckOutFFRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.CheckOutFFResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.GetFileAttachmentRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.GetFileAttachmentResponseType;
import com.agile.ws.schema.attachment.v1.jaxws.GetFileFFRequestType;
import com.agile.ws.schema.attachment.v1.jaxws.GetFileFFResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Attachment_PortType", targetNamespace = "http://xmlns.oracle.com/AgileServices/Core/Attachment/V1")
@XmlSeeAlso({
    com.agile.ws.schema.attachment.v1.jaxws.ObjectFactory.class,
    com.agile.ws.schema.common.v1.jaxws.ObjectFactory.class
})
public interface AttachmentPortType {


    /**
     * 
     * 	  getFileFF retrieves a list of files from a specific Agile file folder object.
     * 	  The request objects consist of specifications of the files to be retrieved while
     * 	  the response object provides comprehensive information about the files retrieved
     * 	  including content, file type, size, and row identifiers.	  
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.GetFileFFResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getFileFF", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.GetFileFF")
    @ResponseWrapper(localName = "getFileFFResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.GetFileFFResponse")
    public GetFileFFResponseType getFileFF(
        @WebParam(name = "request", targetNamespace = "")
        GetFileFFRequestType request);

    /**
     * 
     * 	  getFileAttachment retrieves a specific file from the attachment tab of a particular
     * 	  Agile object. The request object details the specifications of the file to be retrieved
     * 	  and the response object provides comprehensive information about the file retrieved.
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.GetFileAttachmentResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getFileAttachment", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.GetFileAttachment")
    @ResponseWrapper(localName = "getFileAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.GetFileAttachmentResponse")
    public GetFileAttachmentResponseType getFileAttachment(
        @WebParam(name = "request", targetNamespace = "")
        GetFileAttachmentRequestType request);

    /**
     * 
     * 	  addFileAttachment is used to add a new file to the attachment tab of an Agile Object. 	  
     * 	  This is facilitated by specifying relevant details of the new file through the request
     * 	  object.
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.AddFileAttachmentResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "addFileAttachment", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.AddFileAttachment")
    @ResponseWrapper(localName = "addFileAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.AddFileAttachmentResponse")
    public AddFileAttachmentResponseType addFileAttachment(
        @WebParam(name = "request", targetNamespace = "")
        AddFileAttachmentRequestType request);

    /**
     * 
     * 	  checkOutFF is used to check out an Agile file folder object. The request object specifies 
     * 	  the file folder that has to be checked out and the success of the operation may be verified
     * 	  using the status code in the response object. Subsequent operations such as that of adding
     * 	  a file to this file folder and then checking the folder back in are possible after this step.
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.CheckOutFFResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkOutFF", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckOutFF")
    @ResponseWrapper(localName = "checkOutFFResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckOutFFResponse")
    public CheckOutFFResponseType checkOutFF(
        @WebParam(name = "request", targetNamespace = "")
        CheckOutFFRequestType request);

    /**
     * 
     * 	  checkInFF is used to check in an Agile file folder object. The request object specifies the
     * 	  file folder which has already been checked out and needs to be checked in by the webservice
     * 	  operation. Success of the operation may be verified using the status code in the response
     * 	  object.	  
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.CheckInFFResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkInFF", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckInFF")
    @ResponseWrapper(localName = "checkInFFResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckInFFResponse")
    public CheckInFFResponseType checkInFF(
        @WebParam(name = "request", targetNamespace = "")
        CheckInFFRequestType request);

    /**
     * 
     * 	  cancelCheckOutFF is used to cancel the 'checked-out' status of an Agile file File folder object
     * 	  which had been previously checked out by the checkout operation.The request object specifies the
     * 	  file folder for which the 'checked-out' status has to be anulled. Success of the operation may be
     * 	  verified using the status code in the response object.	 
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.CancelCheckOutFFResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "cancelCheckOutFF", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CancelCheckOutFF")
    @ResponseWrapper(localName = "cancelCheckOutFFResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CancelCheckOutFFResponse")
    public CancelCheckOutFFResponseType cancelCheckOutFF(
        @WebParam(name = "request", targetNamespace = "")
        CancelCheckOutFFRequestType request);

    /**
     * 
     * 	  checkOutAttachment is used to check out a specific file from the attachment tab of an Agile object 
     * 	  and to retrieve the contents of the same in the process. The request object specifies the object
     * 	  and file to be retrieved while the desired content is received through the response object.
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.CheckOutAttachmentResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkOutAttachment", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckOutAttachment")
    @ResponseWrapper(localName = "checkOutAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckOutAttachmentResponse")
    public CheckOutAttachmentResponseType checkOutAttachment(
        @WebParam(name = "request", targetNamespace = "")
        CheckOutAttachmentRequestType request);

    /**
     * 
     * 	  checkInAttachment is used to check in an attachment that was previously checked out and possibly
     * 	  modified back into the Agile system. Details of the modified file and its content and the parent
     * 	  object are specified in the request object. Success of the operation may be verified using the
     * 	  status code in the response object.	 	  
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.CheckInAttachmentResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "checkInAttachment", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckInAttachment")
    @ResponseWrapper(localName = "checkInAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.CheckInAttachmentResponse")
    public CheckInAttachmentResponseType checkInAttachment(
        @WebParam(name = "request", targetNamespace = "")
        CheckInAttachmentRequestType request);

    /**
     * 
     * 	  addFileFF is used to a new file to the files tab of an Agile File folder object. The request object
     * 	  specifies details of the file folder that was previously checked out to facilitate the add file process.
     * 	  Success of the operation may be verified using the status code in the response object.	 	  
     * 	  
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.attachment.v1.jaxws.AddFileFFResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "addFileFF", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.AddFileFF")
    @ResponseWrapper(localName = "addFileFFResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Attachment/V1", className = "com.agile.ws.schema.attachment.v1.jaxws.AddFileFFResponse")
    public AddFileFFResponseType addFileFF(
        @WebParam(name = "request", targetNamespace = "")
        AddFileFFRequestType request);

}
