
package com.agile.ws.service.collaboration.v1.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.agile.ws.schema.collaboration.v1.jaxws.AcknowledgeRObjectRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.AcknowledgeRObjectResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.AddApproversRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.AddApproversResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.AddReviewersRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.AddReviewersResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.ApproveRObjectRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.ApproveRObjectResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.AuditRObjectRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.AuditRObjectResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.ChangeStatusRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.ChangeStatusResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.CommentRObjectRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.CommentRObjectResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetAllReviewersRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetAllReviewersResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetApproversRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetApproversResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetReviewersRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetReviewersResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetStatusRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetStatusResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetWorkflowsRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.GetWorkflowsResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.RejectRObjectRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.RejectRObjectResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.RemoveApproversRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.RemoveApproversResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.RemoveReviewersRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.RemoveReviewersResponseType;
import com.agile.ws.schema.collaboration.v1.jaxws.SetWorkFlowRequestType;
import com.agile.ws.schema.collaboration.v1.jaxws.SetWorkFlowResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Collaboration_PortType", targetNamespace = "http://xmlns.oracle.com/AgileServices/Core/Collaboration/V1")
@XmlSeeAlso({
    com.agile.ws.schema.collaboration.v1.jaxws.ObjectFactory.class,
    com.agile.ws.schema.common.v1.jaxws.ObjectFactory.class
})
public interface CollaborationPortType {


    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.GetWorkflowsResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getWorkFlows", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetWorkFlows")
    @ResponseWrapper(localName = "getWorkFlowsResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetWorkFlowsResponse")
    public GetWorkflowsResponseType getWorkFlows(
        @WebParam(name = "request", targetNamespace = "")
        GetWorkflowsRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.GetStatusResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetStatusResponse")
    public GetStatusResponseType getStatus(
        @WebParam(name = "request", targetNamespace = "")
        GetStatusRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.AuditRObjectResponseType
     */
    @WebMethod
    @WebResult(name = "responses", targetNamespace = "")
    @RequestWrapper(localName = "auditRObject", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AuditRObject")
    @ResponseWrapper(localName = "auditRObjectResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AuditRObjectResponse")
    public AuditRObjectResponseType auditRObject(
        @WebParam(name = "request", targetNamespace = "")
        AuditRObjectRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.GetApproversResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getApprovers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetApprovers")
    @ResponseWrapper(localName = "getApproversResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetApproversResponse")
    public GetApproversResponseType getApprovers(
        @WebParam(name = "request", targetNamespace = "")
        GetApproversRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.ChangeStatusResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "changeStatus", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.ChangeStatus")
    @ResponseWrapper(localName = "changeStatusResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.ChangeStatusResponse")
    public ChangeStatusResponseType changeStatus(
        @WebParam(name = "request", targetNamespace = "")
        ChangeStatusRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.ApproveRObjectResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "approveRObject", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.ApproveRObject")
    @ResponseWrapper(localName = "approveRObjectResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.ApproveRObjectResponse")
    public ApproveRObjectResponseType approveRObject(
        @WebParam(name = "request", targetNamespace = "")
        ApproveRObjectRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.RejectRObjectResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "rejectRObject", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RejectRObject")
    @ResponseWrapper(localName = "rejectRObjectResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RejectRObjectResponse")
    public RejectRObjectResponseType rejectRObject(
        @WebParam(name = "request", targetNamespace = "")
        RejectRObjectRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.AcknowledgeRObjectResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "acknowledgeRObject", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AcknowledgeRObject")
    @ResponseWrapper(localName = "acknowledgeRObjectResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AcknowledgeRObjectResponse")
    public AcknowledgeRObjectResponseType acknowledgeRObject(
        @WebParam(name = "request", targetNamespace = "")
        AcknowledgeRObjectRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.SetWorkFlowResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "setWorkFlow", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.SetWorkFlow")
    @ResponseWrapper(localName = "setWorkFlowResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.SetWorkFlowResponse")
    public SetWorkFlowResponseType setWorkFlow(
        @WebParam(name = "request", targetNamespace = "")
        SetWorkFlowRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.AddApproversResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "addApprovers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AddApprovers")
    @ResponseWrapper(localName = "addApproversResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AddApproversResponse")
    public AddApproversResponseType addApprovers(
        @WebParam(name = "request", targetNamespace = "")
        AddApproversRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.RemoveApproversResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "removeApprovers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RemoveApprovers")
    @ResponseWrapper(localName = "removeApproversResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RemoveApproversResponse")
    public RemoveApproversResponseType removeApprovers(
        @WebParam(name = "request", targetNamespace = "")
        RemoveApproversRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.CommentRObjectResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "commentRObject", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.CommentRObject")
    @ResponseWrapper(localName = "commentRObjectResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.CommentRObjectResponse")
    public CommentRObjectResponseType commentRObject(
        @WebParam(name = "request", targetNamespace = "")
        CommentRObjectRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.GetAllReviewersResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getAllReviewers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetAllReviewers")
    @ResponseWrapper(localName = "getAllReviewersResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetAllReviewersResponse")
    public GetAllReviewersResponseType getAllReviewers(
        @WebParam(name = "request", targetNamespace = "")
        GetAllReviewersRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.GetReviewersResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getReviewers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetReviewers")
    @ResponseWrapper(localName = "getReviewersResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.GetReviewersResponse")
    public GetReviewersResponseType getReviewers(
        @WebParam(name = "request", targetNamespace = "")
        GetReviewersRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.AddReviewersResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "addReviewers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AddReviewers")
    @ResponseWrapper(localName = "addReviewersResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.AddReviewersResponse")
    public AddReviewersResponseType addReviewers(
        @WebParam(name = "request", targetNamespace = "")
        AddReviewersRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns com.agile.ws.schema.collaboration.v1.jaxws.RemoveReviewersResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "removeReviewers", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RemoveReviewers")
    @ResponseWrapper(localName = "removeReviewersResponse", targetNamespace = "http://xmlns.oracle.com/AgileObjects/Core/Collaboration/V1", className = "com.agile.ws.schema.collaboration.v1.jaxws.RemoveReviewersResponse")
    public RemoveReviewersResponseType removeReviewers(
        @WebParam(name = "request", targetNamespace = "")
        RemoveReviewersRequestType request);

}
