package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class AssignmentRuleHeader_element extends com.sforce.ws.bind.SoapHeaderObject implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public AssignmentRuleHeader_element() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : assignmentRuleId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean assignmentRuleId__is_set = false;

    private java.lang.String assignmentRuleId;

    public java.lang.String getAssignmentRuleId() {
      return assignmentRuleId;
    }

    public void setAssignmentRuleId(java.lang.String assignmentRuleId) {
      this.assignmentRuleId = assignmentRuleId;
      assignmentRuleId__is_set = true;
    }

    protected void setAssignmentRuleId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("assignmentRuleId", "urn:enterprise.soap.sforce.com","assignmentRuleId","urn:enterprise.soap.sforce.com","ID",1,1,true))) {
        setAssignmentRuleId(__typeMapper.readString(__in, _lookupTypeInfo("assignmentRuleId", "urn:enterprise.soap.sforce.com","assignmentRuleId","urn:enterprise.soap.sforce.com","ID",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldAssignmentRuleId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("assignmentRuleId", "urn:enterprise.soap.sforce.com","assignmentRuleId","urn:enterprise.soap.sforce.com","ID",1,1,true), assignmentRuleId, assignmentRuleId__is_set);
    }

    /**
     * element : useDefaultRule of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: java.lang.Boolean
     */
    private boolean useDefaultRule__is_set = false;

    private java.lang.Boolean useDefaultRule;

    public java.lang.Boolean getUseDefaultRule() {
      return useDefaultRule;
    }

    public void setUseDefaultRule(java.lang.Boolean useDefaultRule) {
      this.useDefaultRule = useDefaultRule;
      useDefaultRule__is_set = true;
    }

    protected void setUseDefaultRule(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("useDefaultRule", "urn:enterprise.soap.sforce.com","useDefaultRule","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setUseDefaultRule((java.lang.Boolean)__typeMapper.readObject(__in, _lookupTypeInfo("useDefaultRule", "urn:enterprise.soap.sforce.com","useDefaultRule","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), java.lang.Boolean.class));
      }
    }

    private void writeFieldUseDefaultRule(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("useDefaultRule", "urn:enterprise.soap.sforce.com","useDefaultRule","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), useDefaultRule, useDefaultRule__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[AssignmentRuleHeader_element ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldAssignmentRuleId(__out, __typeMapper);
      writeFieldUseDefaultRule(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setAssignmentRuleId(__in, __typeMapper);
      setUseDefaultRule(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "assignmentRuleId", assignmentRuleId);
      toStringHelper(sb, "useDefaultRule", useDefaultRule);
    }


}
