package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class DescribeLayout implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public DescribeLayout() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : buttonLayoutSection of type {urn:enterprise.soap.sforce.com}DescribeLayoutButtonSection
     * java type: com.sforce.soap.enterprise.DescribeLayoutButtonSection
     */
    private boolean buttonLayoutSection__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutButtonSection buttonLayoutSection;

    public com.sforce.soap.enterprise.DescribeLayoutButtonSection getButtonLayoutSection() {
      return buttonLayoutSection;
    }

    public void setButtonLayoutSection(com.sforce.soap.enterprise.DescribeLayoutButtonSection buttonLayoutSection) {
      this.buttonLayoutSection = buttonLayoutSection;
      buttonLayoutSection__is_set = true;
    }

    protected void setButtonLayoutSection(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("buttonLayoutSection", "urn:enterprise.soap.sforce.com","buttonLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutButtonSection",0,1,true))) {
        setButtonLayoutSection((com.sforce.soap.enterprise.DescribeLayoutButtonSection)__typeMapper.readObject(__in, _lookupTypeInfo("buttonLayoutSection", "urn:enterprise.soap.sforce.com","buttonLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutButtonSection",0,1,true), com.sforce.soap.enterprise.DescribeLayoutButtonSection.class));
      }
    }

    private void writeFieldButtonLayoutSection(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("buttonLayoutSection", "urn:enterprise.soap.sforce.com","buttonLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutButtonSection",0,1,true), buttonLayoutSection, buttonLayoutSection__is_set);
    }

    /**
     * element : detailLayoutSections of type {urn:enterprise.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.enterprise.DescribeLayoutSection[]
     */
    private boolean detailLayoutSections__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutSection[] detailLayoutSections = new com.sforce.soap.enterprise.DescribeLayoutSection[0];

    public com.sforce.soap.enterprise.DescribeLayoutSection[] getDetailLayoutSections() {
      return detailLayoutSections;
    }

    public void setDetailLayoutSections(com.sforce.soap.enterprise.DescribeLayoutSection[] detailLayoutSections) {
      this.detailLayoutSections = detailLayoutSections;
      detailLayoutSections__is_set = true;
    }

    protected void setDetailLayoutSections(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("detailLayoutSections", "urn:enterprise.soap.sforce.com","detailLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true))) {
        setDetailLayoutSections((com.sforce.soap.enterprise.DescribeLayoutSection[])__typeMapper.readObject(__in, _lookupTypeInfo("detailLayoutSections", "urn:enterprise.soap.sforce.com","detailLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true), com.sforce.soap.enterprise.DescribeLayoutSection[].class));
      }
    }

    private void writeFieldDetailLayoutSections(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("detailLayoutSections", "urn:enterprise.soap.sforce.com","detailLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true), detailLayoutSections, detailLayoutSections__is_set);
    }

    /**
     * element : editLayoutSections of type {urn:enterprise.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.enterprise.DescribeLayoutSection[]
     */
    private boolean editLayoutSections__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutSection[] editLayoutSections = new com.sforce.soap.enterprise.DescribeLayoutSection[0];

    public com.sforce.soap.enterprise.DescribeLayoutSection[] getEditLayoutSections() {
      return editLayoutSections;
    }

    public void setEditLayoutSections(com.sforce.soap.enterprise.DescribeLayoutSection[] editLayoutSections) {
      this.editLayoutSections = editLayoutSections;
      editLayoutSections__is_set = true;
    }

    protected void setEditLayoutSections(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("editLayoutSections", "urn:enterprise.soap.sforce.com","editLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true))) {
        setEditLayoutSections((com.sforce.soap.enterprise.DescribeLayoutSection[])__typeMapper.readObject(__in, _lookupTypeInfo("editLayoutSections", "urn:enterprise.soap.sforce.com","editLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true), com.sforce.soap.enterprise.DescribeLayoutSection[].class));
      }
    }

    private void writeFieldEditLayoutSections(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("editLayoutSections", "urn:enterprise.soap.sforce.com","editLayoutSections","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,-1,true), editLayoutSections, editLayoutSections__is_set);
    }

    /**
     * element : feedView of type {urn:enterprise.soap.sforce.com}DescribeLayoutFeedView
     * java type: com.sforce.soap.enterprise.DescribeLayoutFeedView
     */
    private boolean feedView__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutFeedView feedView;

    public com.sforce.soap.enterprise.DescribeLayoutFeedView getFeedView() {
      return feedView;
    }

    public void setFeedView(com.sforce.soap.enterprise.DescribeLayoutFeedView feedView) {
      this.feedView = feedView;
      feedView__is_set = true;
    }

    protected void setFeedView(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("feedView", "urn:enterprise.soap.sforce.com","feedView","urn:enterprise.soap.sforce.com","DescribeLayoutFeedView",0,1,true))) {
        setFeedView((com.sforce.soap.enterprise.DescribeLayoutFeedView)__typeMapper.readObject(__in, _lookupTypeInfo("feedView", "urn:enterprise.soap.sforce.com","feedView","urn:enterprise.soap.sforce.com","DescribeLayoutFeedView",0,1,true), com.sforce.soap.enterprise.DescribeLayoutFeedView.class));
      }
    }

    private void writeFieldFeedView(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("feedView", "urn:enterprise.soap.sforce.com","feedView","urn:enterprise.soap.sforce.com","DescribeLayoutFeedView",0,1,true), feedView, feedView__is_set);
    }

    /**
     * element : highlightsPanelLayoutSection of type {urn:enterprise.soap.sforce.com}DescribeLayoutSection
     * java type: com.sforce.soap.enterprise.DescribeLayoutSection
     */
    private boolean highlightsPanelLayoutSection__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutSection highlightsPanelLayoutSection;

    public com.sforce.soap.enterprise.DescribeLayoutSection getHighlightsPanelLayoutSection() {
      return highlightsPanelLayoutSection;
    }

    public void setHighlightsPanelLayoutSection(com.sforce.soap.enterprise.DescribeLayoutSection highlightsPanelLayoutSection) {
      this.highlightsPanelLayoutSection = highlightsPanelLayoutSection;
      highlightsPanelLayoutSection__is_set = true;
    }

    protected void setHighlightsPanelLayoutSection(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("highlightsPanelLayoutSection", "urn:enterprise.soap.sforce.com","highlightsPanelLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,1,true))) {
        setHighlightsPanelLayoutSection((com.sforce.soap.enterprise.DescribeLayoutSection)__typeMapper.readObject(__in, _lookupTypeInfo("highlightsPanelLayoutSection", "urn:enterprise.soap.sforce.com","highlightsPanelLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,1,true), com.sforce.soap.enterprise.DescribeLayoutSection.class));
      }
    }

    private void writeFieldHighlightsPanelLayoutSection(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("highlightsPanelLayoutSection", "urn:enterprise.soap.sforce.com","highlightsPanelLayoutSection","urn:enterprise.soap.sforce.com","DescribeLayoutSection",0,1,true), highlightsPanelLayoutSection, highlightsPanelLayoutSection__is_set);
    }

    /**
     * element : id of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean id__is_set = false;

    private java.lang.String id;

    public java.lang.String getId() {
      return id;
    }

    public void setId(java.lang.String id) {
      this.id = id;
      id__is_set = true;
    }

    protected void setId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("id", "urn:enterprise.soap.sforce.com","id","urn:enterprise.soap.sforce.com","ID",1,1,true))) {
        setId(__typeMapper.readString(__in, _lookupTypeInfo("id", "urn:enterprise.soap.sforce.com","id","urn:enterprise.soap.sforce.com","ID",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("id", "urn:enterprise.soap.sforce.com","id","urn:enterprise.soap.sforce.com","ID",1,1,true), id, id__is_set);
    }

    /**
     * element : quickActionList of type {urn:enterprise.soap.sforce.com}DescribeQuickActionListResult
     * java type: com.sforce.soap.enterprise.DescribeQuickActionListResult
     */
    private boolean quickActionList__is_set = false;

    private com.sforce.soap.enterprise.DescribeQuickActionListResult quickActionList;

    public com.sforce.soap.enterprise.DescribeQuickActionListResult getQuickActionList() {
      return quickActionList;
    }

    public void setQuickActionList(com.sforce.soap.enterprise.DescribeQuickActionListResult quickActionList) {
      this.quickActionList = quickActionList;
      quickActionList__is_set = true;
    }

    protected void setQuickActionList(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("quickActionList", "urn:enterprise.soap.sforce.com","quickActionList","urn:enterprise.soap.sforce.com","DescribeQuickActionListResult",0,1,true))) {
        setQuickActionList((com.sforce.soap.enterprise.DescribeQuickActionListResult)__typeMapper.readObject(__in, _lookupTypeInfo("quickActionList", "urn:enterprise.soap.sforce.com","quickActionList","urn:enterprise.soap.sforce.com","DescribeQuickActionListResult",0,1,true), com.sforce.soap.enterprise.DescribeQuickActionListResult.class));
      }
    }

    private void writeFieldQuickActionList(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("quickActionList", "urn:enterprise.soap.sforce.com","quickActionList","urn:enterprise.soap.sforce.com","DescribeQuickActionListResult",0,1,true), quickActionList, quickActionList__is_set);
    }

    /**
     * element : relatedContent of type {urn:enterprise.soap.sforce.com}RelatedContent
     * java type: com.sforce.soap.enterprise.RelatedContent
     */
    private boolean relatedContent__is_set = false;

    private com.sforce.soap.enterprise.RelatedContent relatedContent;

    public com.sforce.soap.enterprise.RelatedContent getRelatedContent() {
      return relatedContent;
    }

    public void setRelatedContent(com.sforce.soap.enterprise.RelatedContent relatedContent) {
      this.relatedContent = relatedContent;
      relatedContent__is_set = true;
    }

    protected void setRelatedContent(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("relatedContent", "urn:enterprise.soap.sforce.com","relatedContent","urn:enterprise.soap.sforce.com","RelatedContent",0,1,true))) {
        setRelatedContent((com.sforce.soap.enterprise.RelatedContent)__typeMapper.readObject(__in, _lookupTypeInfo("relatedContent", "urn:enterprise.soap.sforce.com","relatedContent","urn:enterprise.soap.sforce.com","RelatedContent",0,1,true), com.sforce.soap.enterprise.RelatedContent.class));
      }
    }

    private void writeFieldRelatedContent(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("relatedContent", "urn:enterprise.soap.sforce.com","relatedContent","urn:enterprise.soap.sforce.com","RelatedContent",0,1,true), relatedContent, relatedContent__is_set);
    }

    /**
     * element : relatedLists of type {urn:enterprise.soap.sforce.com}RelatedList
     * java type: com.sforce.soap.enterprise.RelatedList[]
     */
    private boolean relatedLists__is_set = false;

    private com.sforce.soap.enterprise.RelatedList[] relatedLists = new com.sforce.soap.enterprise.RelatedList[0];

    public com.sforce.soap.enterprise.RelatedList[] getRelatedLists() {
      return relatedLists;
    }

    public void setRelatedLists(com.sforce.soap.enterprise.RelatedList[] relatedLists) {
      this.relatedLists = relatedLists;
      relatedLists__is_set = true;
    }

    protected void setRelatedLists(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("relatedLists", "urn:enterprise.soap.sforce.com","relatedLists","urn:enterprise.soap.sforce.com","RelatedList",0,-1,true))) {
        setRelatedLists((com.sforce.soap.enterprise.RelatedList[])__typeMapper.readObject(__in, _lookupTypeInfo("relatedLists", "urn:enterprise.soap.sforce.com","relatedLists","urn:enterprise.soap.sforce.com","RelatedList",0,-1,true), com.sforce.soap.enterprise.RelatedList[].class));
      }
    }

    private void writeFieldRelatedLists(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("relatedLists", "urn:enterprise.soap.sforce.com","relatedLists","urn:enterprise.soap.sforce.com","RelatedList",0,-1,true), relatedLists, relatedLists__is_set);
    }

    /**
     * element : saveOptions of type {urn:enterprise.soap.sforce.com}DescribeLayoutSaveOption
     * java type: com.sforce.soap.enterprise.DescribeLayoutSaveOption[]
     */
    private boolean saveOptions__is_set = false;

    private com.sforce.soap.enterprise.DescribeLayoutSaveOption[] saveOptions = new com.sforce.soap.enterprise.DescribeLayoutSaveOption[0];

    public com.sforce.soap.enterprise.DescribeLayoutSaveOption[] getSaveOptions() {
      return saveOptions;
    }

    public void setSaveOptions(com.sforce.soap.enterprise.DescribeLayoutSaveOption[] saveOptions) {
      this.saveOptions = saveOptions;
      saveOptions__is_set = true;
    }

    protected void setSaveOptions(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("saveOptions", "urn:enterprise.soap.sforce.com","saveOptions","urn:enterprise.soap.sforce.com","DescribeLayoutSaveOption",0,-1,true))) {
        setSaveOptions((com.sforce.soap.enterprise.DescribeLayoutSaveOption[])__typeMapper.readObject(__in, _lookupTypeInfo("saveOptions", "urn:enterprise.soap.sforce.com","saveOptions","urn:enterprise.soap.sforce.com","DescribeLayoutSaveOption",0,-1,true), com.sforce.soap.enterprise.DescribeLayoutSaveOption[].class));
      }
    }

    private void writeFieldSaveOptions(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("saveOptions", "urn:enterprise.soap.sforce.com","saveOptions","urn:enterprise.soap.sforce.com","DescribeLayoutSaveOption",0,-1,true), saveOptions, saveOptions__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[DescribeLayout ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldButtonLayoutSection(__out, __typeMapper);
      writeFieldDetailLayoutSections(__out, __typeMapper);
      writeFieldEditLayoutSections(__out, __typeMapper);
      writeFieldFeedView(__out, __typeMapper);
      writeFieldHighlightsPanelLayoutSection(__out, __typeMapper);
      writeFieldId(__out, __typeMapper);
      writeFieldQuickActionList(__out, __typeMapper);
      writeFieldRelatedContent(__out, __typeMapper);
      writeFieldRelatedLists(__out, __typeMapper);
      writeFieldSaveOptions(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setButtonLayoutSection(__in, __typeMapper);
      setDetailLayoutSections(__in, __typeMapper);
      setEditLayoutSections(__in, __typeMapper);
      setFeedView(__in, __typeMapper);
      setHighlightsPanelLayoutSection(__in, __typeMapper);
      setId(__in, __typeMapper);
      setQuickActionList(__in, __typeMapper);
      setRelatedContent(__in, __typeMapper);
      setRelatedLists(__in, __typeMapper);
      setSaveOptions(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "buttonLayoutSection", buttonLayoutSection);
      toStringHelper(sb, "detailLayoutSections", detailLayoutSections);
      toStringHelper(sb, "editLayoutSections", editLayoutSections);
      toStringHelper(sb, "feedView", feedView);
      toStringHelper(sb, "highlightsPanelLayoutSection", highlightsPanelLayoutSection);
      toStringHelper(sb, "id", id);
      toStringHelper(sb, "quickActionList", quickActionList);
      toStringHelper(sb, "relatedContent", relatedContent);
      toStringHelper(sb, "relatedLists", relatedLists);
      toStringHelper(sb, "saveOptions", saveOptions);
    }


}
