package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class EmailHeader_element extends com.sforce.ws.bind.SoapHeaderObject implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public EmailHeader_element() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : triggerAutoResponseEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean triggerAutoResponseEmail__is_set = false;

    private boolean triggerAutoResponseEmail;

    public boolean getTriggerAutoResponseEmail() {
      return triggerAutoResponseEmail;
    }

    public boolean isTriggerAutoResponseEmail() {
      return triggerAutoResponseEmail;
    }

    public void setTriggerAutoResponseEmail(boolean triggerAutoResponseEmail) {
      this.triggerAutoResponseEmail = triggerAutoResponseEmail;
      triggerAutoResponseEmail__is_set = true;
    }

    protected void setTriggerAutoResponseEmail(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("triggerAutoResponseEmail", "urn:enterprise.soap.sforce.com","triggerAutoResponseEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setTriggerAutoResponseEmail(__typeMapper.readBoolean(__in, _lookupTypeInfo("triggerAutoResponseEmail", "urn:enterprise.soap.sforce.com","triggerAutoResponseEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldTriggerAutoResponseEmail(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("triggerAutoResponseEmail", "urn:enterprise.soap.sforce.com","triggerAutoResponseEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), triggerAutoResponseEmail, triggerAutoResponseEmail__is_set);
    }

    /**
     * element : triggerOtherEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean triggerOtherEmail__is_set = false;

    private boolean triggerOtherEmail;

    public boolean getTriggerOtherEmail() {
      return triggerOtherEmail;
    }

    public boolean isTriggerOtherEmail() {
      return triggerOtherEmail;
    }

    public void setTriggerOtherEmail(boolean triggerOtherEmail) {
      this.triggerOtherEmail = triggerOtherEmail;
      triggerOtherEmail__is_set = true;
    }

    protected void setTriggerOtherEmail(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("triggerOtherEmail", "urn:enterprise.soap.sforce.com","triggerOtherEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setTriggerOtherEmail(__typeMapper.readBoolean(__in, _lookupTypeInfo("triggerOtherEmail", "urn:enterprise.soap.sforce.com","triggerOtherEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldTriggerOtherEmail(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("triggerOtherEmail", "urn:enterprise.soap.sforce.com","triggerOtherEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), triggerOtherEmail, triggerOtherEmail__is_set);
    }

    /**
     * element : triggerUserEmail of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean triggerUserEmail__is_set = false;

    private boolean triggerUserEmail;

    public boolean getTriggerUserEmail() {
      return triggerUserEmail;
    }

    public boolean isTriggerUserEmail() {
      return triggerUserEmail;
    }

    public void setTriggerUserEmail(boolean triggerUserEmail) {
      this.triggerUserEmail = triggerUserEmail;
      triggerUserEmail__is_set = true;
    }

    protected void setTriggerUserEmail(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("triggerUserEmail", "urn:enterprise.soap.sforce.com","triggerUserEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setTriggerUserEmail(__typeMapper.readBoolean(__in, _lookupTypeInfo("triggerUserEmail", "urn:enterprise.soap.sforce.com","triggerUserEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldTriggerUserEmail(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("triggerUserEmail", "urn:enterprise.soap.sforce.com","triggerUserEmail","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), triggerUserEmail, triggerUserEmail__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       super.writeFields(__out, __typeMapper);
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        super.loadFields(__in, __typeMapper);
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[EmailHeader_element ");
      sb.append(super.toString());
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldTriggerAutoResponseEmail(__out, __typeMapper);
      writeFieldTriggerOtherEmail(__out, __typeMapper);
      writeFieldTriggerUserEmail(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setTriggerAutoResponseEmail(__in, __typeMapper);
      setTriggerOtherEmail(__in, __typeMapper);
      setTriggerUserEmail(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "triggerAutoResponseEmail", triggerAutoResponseEmail);
      toStringHelper(sb, "triggerOtherEmail", triggerOtherEmail);
      toStringHelper(sb, "triggerUserEmail", triggerUserEmail);
    }


}
