package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class Location implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public Location() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : latitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private boolean latitude__is_set = false;

    private java.lang.Double latitude;

    public java.lang.Double getLatitude() {
      return latitude;
    }

    public void setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      latitude__is_set = true;
    }

    protected void setLatitude(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("latitude", "urn:enterprise.soap.sforce.com","latitude","http://www.w3.org/2001/XMLSchema","double",1,1,true))) {
        setLatitude((java.lang.Double)__typeMapper.readObject(__in, _lookupTypeInfo("latitude", "urn:enterprise.soap.sforce.com","latitude","http://www.w3.org/2001/XMLSchema","double",1,1,true), java.lang.Double.class));
      }
    }

    private void writeFieldLatitude(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("latitude", "urn:enterprise.soap.sforce.com","latitude","http://www.w3.org/2001/XMLSchema","double",1,1,true), latitude, latitude__is_set);
    }

    /**
     * element : longitude of type {http://www.w3.org/2001/XMLSchema}double
     * java type: java.lang.Double
     */
    private boolean longitude__is_set = false;

    private java.lang.Double longitude;

    public java.lang.Double getLongitude() {
      return longitude;
    }

    public void setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      longitude__is_set = true;
    }

    protected void setLongitude(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("longitude", "urn:enterprise.soap.sforce.com","longitude","http://www.w3.org/2001/XMLSchema","double",1,1,true))) {
        setLongitude((java.lang.Double)__typeMapper.readObject(__in, _lookupTypeInfo("longitude", "urn:enterprise.soap.sforce.com","longitude","http://www.w3.org/2001/XMLSchema","double",1,1,true), java.lang.Double.class));
      }
    }

    private void writeFieldLongitude(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("longitude", "urn:enterprise.soap.sforce.com","longitude","http://www.w3.org/2001/XMLSchema","double",1,1,true), longitude, longitude__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[Location ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldLatitude(__out, __typeMapper);
      writeFieldLongitude(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setLatitude(__in, __typeMapper);
      setLongitude(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "latitude", latitude);
      toStringHelper(sb, "longitude", longitude);
    }


}
