package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class OwnerChangeOption implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public OwnerChangeOption() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : type of type {urn:enterprise.soap.sforce.com}OwnerChangeOptionType
     * java type: com.sforce.soap.enterprise.OwnerChangeOptionType
     */
    private boolean type__is_set = false;

    private com.sforce.soap.enterprise.OwnerChangeOptionType type;

    public com.sforce.soap.enterprise.OwnerChangeOptionType getType() {
      return type;
    }

    public void setType(com.sforce.soap.enterprise.OwnerChangeOptionType type) {
      this.type = type;
      type__is_set = true;
    }

    protected void setType(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("type", "urn:enterprise.soap.sforce.com","type","urn:enterprise.soap.sforce.com","OwnerChangeOptionType",1,1,true))) {
        setType((com.sforce.soap.enterprise.OwnerChangeOptionType)__typeMapper.readObject(__in, _lookupTypeInfo("type", "urn:enterprise.soap.sforce.com","type","urn:enterprise.soap.sforce.com","OwnerChangeOptionType",1,1,true), com.sforce.soap.enterprise.OwnerChangeOptionType.class));
      }
    }

    private void writeFieldType(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("type", "urn:enterprise.soap.sforce.com","type","urn:enterprise.soap.sforce.com","OwnerChangeOptionType",1,1,true), type, type__is_set);
    }

    /**
     * element : execute of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private boolean execute__is_set = false;

    private boolean execute;

    public boolean getExecute() {
      return execute;
    }

    public boolean isExecute() {
      return execute;
    }

    public void setExecute(boolean execute) {
      this.execute = execute;
      execute__is_set = true;
    }

    protected void setExecute(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("execute", "urn:enterprise.soap.sforce.com","execute","http://www.w3.org/2001/XMLSchema","boolean",1,1,true))) {
        setExecute(__typeMapper.readBoolean(__in, _lookupTypeInfo("execute", "urn:enterprise.soap.sforce.com","execute","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), boolean.class));
      }
    }

    private void writeFieldExecute(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("execute", "urn:enterprise.soap.sforce.com","execute","http://www.w3.org/2001/XMLSchema","boolean",1,1,true), execute, execute__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[OwnerChangeOption ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldType(__out, __typeMapper);
      writeFieldExecute(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setType(__in, __typeMapper);
      setExecute(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "type", type);
      toStringHelper(sb, "execute", execute);
    }


}
