package com.sforce.soap.enterprise;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class SendEmailError implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public SendEmailError() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

    /**
     * element : fields of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private boolean fields__is_set = false;

    private java.lang.String[] fields = new java.lang.String[0];

    public java.lang.String[] getFields() {
      return fields;
    }

    public void setFields(java.lang.String[] fields) {
      this.fields = fields;
      fields__is_set = true;
    }

    protected void setFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.isElement(__in, _lookupTypeInfo("fields", "urn:enterprise.soap.sforce.com","fields","http://www.w3.org/2001/XMLSchema","string",0,-1,true))) {
        setFields((java.lang.String[])__typeMapper.readObject(__in, _lookupTypeInfo("fields", "urn:enterprise.soap.sforce.com","fields","http://www.w3.org/2001/XMLSchema","string",0,-1,true), java.lang.String[].class));
      }
    }

    private void writeFieldFields(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("fields", "urn:enterprise.soap.sforce.com","fields","http://www.w3.org/2001/XMLSchema","string",0,-1,true), fields, fields__is_set);
    }

    /**
     * element : message of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private boolean message__is_set = false;

    private java.lang.String message;

    public java.lang.String getMessage() {
      return message;
    }

    public void setMessage(java.lang.String message) {
      this.message = message;
      message__is_set = true;
    }

    protected void setMessage(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("message", "urn:enterprise.soap.sforce.com","message","http://www.w3.org/2001/XMLSchema","string",1,1,true))) {
        setMessage(__typeMapper.readString(__in, _lookupTypeInfo("message", "urn:enterprise.soap.sforce.com","message","http://www.w3.org/2001/XMLSchema","string",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldMessage(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("message", "urn:enterprise.soap.sforce.com","message","http://www.w3.org/2001/XMLSchema","string",1,1,true), message, message__is_set);
    }

    /**
     * element : statusCode of type {urn:enterprise.soap.sforce.com}StatusCode
     * java type: com.sforce.soap.enterprise.StatusCode
     */
    private boolean statusCode__is_set = false;

    private com.sforce.soap.enterprise.StatusCode statusCode;

    public com.sforce.soap.enterprise.StatusCode getStatusCode() {
      return statusCode;
    }

    public void setStatusCode(com.sforce.soap.enterprise.StatusCode statusCode) {
      this.statusCode = statusCode;
      statusCode__is_set = true;
    }

    protected void setStatusCode(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("statusCode", "urn:enterprise.soap.sforce.com","statusCode","urn:enterprise.soap.sforce.com","StatusCode",1,1,true))) {
        setStatusCode((com.sforce.soap.enterprise.StatusCode)__typeMapper.readObject(__in, _lookupTypeInfo("statusCode", "urn:enterprise.soap.sforce.com","statusCode","urn:enterprise.soap.sforce.com","StatusCode",1,1,true), com.sforce.soap.enterprise.StatusCode.class));
      }
    }

    private void writeFieldStatusCode(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("statusCode", "urn:enterprise.soap.sforce.com","statusCode","urn:enterprise.soap.sforce.com","StatusCode",1,1,true), statusCode, statusCode__is_set);
    }

    /**
     * element : targetObjectId of type {urn:enterprise.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private boolean targetObjectId__is_set = false;

    private java.lang.String targetObjectId;

    public java.lang.String getTargetObjectId() {
      return targetObjectId;
    }

    public void setTargetObjectId(java.lang.String targetObjectId) {
      this.targetObjectId = targetObjectId;
      targetObjectId__is_set = true;
    }

    protected void setTargetObjectId(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __in.peekTag();
      if (__typeMapper.verifyElement(__in, _lookupTypeInfo("targetObjectId", "urn:enterprise.soap.sforce.com","targetObjectId","urn:enterprise.soap.sforce.com","ID",1,1,true))) {
        setTargetObjectId(__typeMapper.readString(__in, _lookupTypeInfo("targetObjectId", "urn:enterprise.soap.sforce.com","targetObjectId","urn:enterprise.soap.sforce.com","ID",1,1,true), java.lang.String.class));
      }
    }

    private void writeFieldTargetObjectId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      __typeMapper.writeObject(__out, _lookupTypeInfo("targetObjectId", "urn:enterprise.soap.sforce.com","targetObjectId","urn:enterprise.soap.sforce.com","ID",1,1,true), targetObjectId, targetObjectId__is_set);
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       writeFields1(__out, __typeMapper);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        loadFields1(__in, __typeMapper);
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[SendEmailError ");
      toString1(sb);

      sb.append("]\n");
      return sb.toString();
    }

    private void toStringHelper(StringBuilder sb, String name, Object value) {
      sb.append(' ').append(name).append("='").append(com.sforce.ws.util.Verbose.toString(value)).append("'\n");
    }

    private void writeFields1(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
      writeFieldFields(__out, __typeMapper);
      writeFieldMessage(__out, __typeMapper);
      writeFieldStatusCode(__out, __typeMapper);
      writeFieldTargetObjectId(__out, __typeMapper);
    }

    private void loadFields1(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      setFields(__in, __typeMapper);
      setMessage(__in, __typeMapper);
      setStatusCode(__in, __typeMapper);
      setTargetObjectId(__in, __typeMapper);
    }

    private void toString1(StringBuilder sb) {
      toStringHelper(sb, "fields", fields);
      toStringHelper(sb, "message", message);
      toStringHelper(sb, "statusCode", statusCode);
      toStringHelper(sb, "targetObjectId", targetObjectId);
    }


}
